-- Скрипт для воссоздания схемы E3_ADMIN
-- Сгенерировано: 2025-09-25 12:42:47

CREATE TABLE "E3_ADMIN"."Assembly" (
    "LPNTR" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "FLAGS" NUMBER,
    "NAME" VARCHAR2(80 CHAR),
    "SUBENTRY" VARCHAR2(255 CHAR),
    "SUBVERSION" VARCHAR2(4 CHAR),
    PRIMARY KEY ("LPNTR", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."AttributeDefinition" (
    "AttributeID" NUMBER,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE,
    "Typ" NUMBER,
    "Owner" NUMBER,
    "Owner2" NUMBER,
    "SingleInstance" NUMBER(1, 0),
    "MustExist" NUMBER(1, 0),
    "Hidden" NUMBER(1, 0),
    "Format" VARCHAR2(80 CHAR),
    "PositionX" FLOAT(126),
    "PositionY" FLOAT(126),
    "Visible" NUMBER,
    "Color" NUMBER,
    "Ratio" NUMBER,
    "Size" FLOAT(126),
    "Direction" NUMBER,
    "Level" NUMBER,
    "DefaultValue" VARCHAR2(255 CHAR),
    "ASSIGNED_LIST" VARCHAR2(255 CHAR),
    "UNIQUE_VALUE" NUMBER,
    "Flags2" NUMBER,
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR),
    "USAGE_DESCRIPTION" VARCHAR2(50 CHAR),
    PRIMARY KEY ("AttributeName") ENABLE
);

CREATE TABLE "E3_ADMIN"."ATTRIBUTE_LISTS" (
    "ID" NUMBER NOT NULL ENABLE,
    "ASSIGNED_LIST" VARCHAR2(255 CHAR),
    "READ_ONLY" NUMBER(1, 0),
    "LOWER" FLOAT(126),
    "UPPER" FLOAT(126),
    PRIMARY KEY ("ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."ATTRIBUTE_LIST_VALUES" (
    "ID" NUMBER NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "VALUE" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."BlockedInfos" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE,
    "RootEntry" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "BlockedPins" BLOB,
    PRIMARY KEY ("ENTRY", "VERSION", "RootEntry") ENABLE
);

CREATE TABLE "E3_ADMIN"."Cable" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "BundleID" NUMBER,
    "ParentID" NUMBER,
    "Name" VARCHAR2(64 CHAR),
    "NODENO" NUMBER,
    "CrossSection" FLOAT(126),
    "Color" NUMBER,
    "Flags" NUMBER,
    "SUBENTRY" VARCHAR2(255 CHAR),
    "SUBVERSION" VARCHAR2(4 CHAR),
    "OuterDia" FLOAT(126),
    PRIMARY KEY ("ENTRY", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."ColumnDescription" (
    "TableName" VARCHAR2(128 CHAR) NOT NULL ENABLE,
    "ColumnName" VARCHAR2(128 CHAR) NOT NULL ENABLE,
    "English" VARCHAR2(80 CHAR),
    "German" VARCHAR2(80 CHAR),
    "French" VARCHAR2(80 CHAR),
    "Chinese" VARCHAR2(80 CHAR),
    "Dutch" VARCHAR2(80 CHAR),
    "Italian" VARCHAR2(80 CHAR),
    "Japanese" VARCHAR2(80 CHAR),
    "Polski" VARCHAR2(255 CHAR),
    "Portuguese" VARCHAR2(80 CHAR),
    "Russian" VARCHAR2(80 CHAR),
    "Spanish" VARCHAR2(80 CHAR),
    "Turkish" VARCHAR2(80 CHAR),
    PRIMARY KEY ("TableName", "ColumnName") ENABLE
);

CREATE TABLE "E3_ADMIN"."ComponentAttribute" (
    "ID" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE,
    "BundleID" NUMBER NOT NULL ENABLE,
    "NODENO" NUMBER NOT NULL ENABLE,
    "Flags" NUMBER NOT NULL ENABLE,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER NOT NULL ENABLE,
    "AttributeValue" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID", "ENTRY", "VERSION", "BundleID", "NODENO", "Flags", "AttributeName", "Copy") ENABLE
);

CREATE TABLE "E3_ADMIN"."ComponentClassification" (
    "Name" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "Structure" BLOB,
    PRIMARY KEY ("Name") ENABLE
);

CREATE TABLE "E3_ADMIN"."ComponentData" (
    "ID" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "ENTRY" VARCHAR2(255 CHAR),
    "VERSION" VARCHAR2(4 CHAR),
    "DeviceLetterCode" VARCHAR2(4 CHAR),
    "Class" VARCHAR2(80 CHAR),
    "ENTRYTYP" NUMBER,
    "Description" VARCHAR2(255 CHAR),
    "LPNTR" VARCHAR2(255 CHAR),
    "VSTATUS" VARCHAR2(1 CHAR),
    "VersionText" VARCHAR2(80 CHAR),
    "DATEMAIN" DATE,
    "LASTUPDT" DATE,
    "MPNTR" VARCHAR2(255 CHAR),
    "Flags" NUMBER,
    "ArticleNumber" VARCHAR2(80 CHAR),
    "Supplier" VARCHAR2(80 CHAR),
    "SPNTR" VARCHAR2(20 CHAR),
    "SUBTYP" NUMBER,
    "*Normative_doc" VARCHAR2(255 CHAR),
    "*Owner" VARCHAR2(80 CHAR),
    "*SAP_nomer" VARCHAR2(128 CHAR),
    "Class-main" VARCHAR2(80 CHAR),
    "TC_ID" VARCHAR2(128 CHAR),
    PRIMARY KEY ("ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."COMPONENT_STATES" (
    "ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "NAME" VARCHAR2(255 CHAR),
    "COMP_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "SYMBOL_STATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "GATNUM" NUMBER NOT NULL ENABLE,
    "ORDER_NUM" NUMBER,
    PRIMARY KEY ("ID", "COMP_ID", "SYMBOL_STATE_ID", "GATNUM") ENABLE
);

CREATE TABLE "E3_ADMIN"."ConnectionTypes" (
    "ConnectionType" NUMBER NOT NULL ENABLE,
    "Flags" NUMBER,
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ConnectionType") ENABLE
);

CREATE TABLE "E3_ADMIN"."CR_ATTRIBUTES" (
    "CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "VALUE" VARCHAR2(255 CHAR),
    PRIMARY KEY ("CRIMPING_RULES_GUID", "NAME", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."CRIMPING_RULES" (
    "GUID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "PHSYPIN_ENTRY" VARCHAR2(255 CHAR),
    "PHYSPIN_PIN_NUMBER" NUMBER,
    "RULE_ID" NUMBER,
    "DESCRIPTION" VARCHAR2(255 CHAR),
    "RULE_TYPE" NUMBER,
    PRIMARY KEY ("GUID") ENABLE
);

CREATE TABLE "E3_ADMIN"."CrossSections" (
    "ID" NUMBER NOT NULL ENABLE,
    "CrossSection" FLOAT(126) NOT NULL ENABLE,
    "Description" VARCHAR2(255 CHAR),
    "Flags" NUMBER,
    "Type" NUMBER,
    PRIMARY KEY ("ID", "CrossSection") ENABLE
);

CREATE TABLE "E3_ADMIN"."CR_WIRE_DEFINITION_ATTRIBUTES" (
    "CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "CR_WIRE_DEFINITIONS_INDEX" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "VALUE" VARCHAR2(255 CHAR),
    "RANGE_MAX" VARCHAR2(255 CHAR),
    "FLAGS" NUMBER,
    PRIMARY KEY ("CRIMPING_RULES_GUID", "CR_WIRE_DEFINITIONS_INDEX", "NAME", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."CR_WIRE_DEFINITIONS" (
    "CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "INDEX" NUMBER NOT NULL ENABLE,
    "MIN_SIZE" FLOAT(126),
    "MAX_SIZE" FLOAT(126),
    PRIMARY KEY ("CRIMPING_RULES_GUID", "INDEX") ENABLE
);

CREATE TABLE "E3_ADMIN"."DatabaseInfo" (
    "Version" VARCHAR2(10 CHAR) NOT NULL ENABLE,
    "Description" VARCHAR2(255 CHAR),
    PRIMARY KEY ("Version") ENABLE
);

CREATE TABLE "E3_ADMIN"."DatabaseTree" (
    "Structure" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "Data" BLOB,
    "TreeType" NUMBER NOT NULL ENABLE,
    "Active" NUMBER(1, 0),
    PRIMARY KEY ("Structure", "TreeType") ENABLE
);

CREATE TABLE "E3_ADMIN"."Drill" (
    "EntryID" NUMBER NOT NULL ENABLE,
    "Diameter" FLOAT(126),
    "Tolerance" FLOAT(126),
    "Unit" VARCHAR2(20 CHAR),
    "Type" NUMBER,
    "TData" BLOB,
    PRIMARY KEY ("EntryID") ENABLE
);

CREATE TABLE "E3_ADMIN"."ELECTRICAL_ATTRIBUTES" (
    "WIREKIND_ID" NUMBER NOT NULL ENABLE,
    "RELATIVE_PERMITTIVITY" FLOAT(126),
    "LOSS_ANGLE" FLOAT(126),
    PRIMARY KEY ("WIREKIND_ID") ENABLE
);


CREATE TABLE "E3_ADMIN"."FAVORITES" (
    "ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 CHAR),
    "TYPE" NUMBER,
    "SEQUENCE" NUMBER,
    PRIMARY KEY ("ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."FAVORITE_VALUES" (
    "ID" NUMBER NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "DBFIELD" VARCHAR2(255 CHAR),
    "DESCRIPTION" VARCHAR2(255 CHAR),
    "VALUE" VARCHAR2(255 CHAR),
    "FLAGS" NUMBER,
    PRIMARY KEY ("ID", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."FUNCTIONAL_ASSIGNMENTS" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE,
    "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "PINCOPY" NUMBER NOT NULL ENABLE,
    "FUNAME" VARCHAR2(255 CHAR),
    "FUID" NUMBER,
    "FUPORT" NUMBER,
    PRIMARY KEY ("ENTRY", "VERSION", "NAME", "PINCOPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."FUNCTIONAL_PORTS" (
    "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "ID" NUMBER NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "PORT" VARCHAR2(255 CHAR),
    "FLAGS" NUMBER,
    PRIMARY KEY ("NAME", "ID", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."FUNCTIONAL_UNITS" (
    "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "ID" NUMBER NOT NULL ENABLE,
    "SYMBOL" VARCHAR2(255 CHAR),
    "TYPE" NUMBER,
    PRIMARY KEY ("NAME", "ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."FUNCTIONAL_UNIT_STATES" (
    "ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "NAME" VARCHAR2(255 CHAR),
    "FU_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "FU_ID" NUMBER NOT NULL ENABLE,
    "ORDER_NUM" NUMBER,
    "FLAGS" NUMBER,
    PRIMARY KEY ("ID", "FU_NAME", "FU_ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."FUNCTION_ATTRIBUTES" (
    "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "ID" NUMBER NOT NULL ENABLE,
    "PORT_NUMBER" NUMBER NOT NULL ENABLE,
    "ATTRIBUTE_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "STATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "ATTRIBUTE_VALUE" VARCHAR2(255 CHAR),
    PRIMARY KEY ("NAME", "ID", "PORT_NUMBER", "ATTRIBUTE_NAME", "COPY", "STATE_ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."Gate" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "CCTNAME" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ENTRY", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."GATE_FUNCTION_ATTRIBUTES" (
    "LPNTR" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "GateNumber" NUMBER NOT NULL ENABLE,
    "FUSUBID" NUMBER NOT NULL ENABLE,
    "STATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER NOT NULL ENABLE,
    "AttributeValue" VARCHAR2(255 CHAR),
    PRIMARY KEY ("LPNTR", "GateNumber", "FUSUBID", "STATE_ID", "AttributeName", "Copy") ENABLE
);

CREATE TABLE "E3_ADMIN"."GatePinRelation" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "GateNumber" NUMBER NOT NULL ENABLE,
    "PinNumber" NUMBER NOT NULL ENABLE,
    "Representation" NUMBER NOT NULL ENABLE,
    "NodeNumber" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("ENTRY", "GateNumber", "PinNumber", "Representation", "NodeNumber") ENABLE
);

CREATE TABLE "E3_ADMIN"."IEC 750 letter codes" (
    "ID" NUMBER NOT NULL ENABLE,
    "LetterCode" VARCHAR2(255 CHAR),
    "ValueRange" VARCHAR2(255 CHAR),
    "Class" VARCHAR2(255 CHAR),
    "Klasse" VARCHAR2(255 CHAR),
    "Classe" VARCHAR2(255 CHAR),
    "Clase" VARCHAR2(255 CHAR),
    "Eeann" VARCHAR2(256 CHAR),
    PRIMARY KEY ("ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."Languages" (
    "<mainClass>" VARCHAR2(255 CHAR),
    "<subClass>" VARCHAR2(255 CHAR),
    "American English" VARCHAR2(255 CHAR),
    "British English" VARCHAR2(255 CHAR),
    "Castellano" VARCHAR2(255 CHAR),
    "Chinese" VARCHAR2(255 CHAR),
    "Chinese(CHT)" VARCHAR2(255 CHAR),
    "Description" VARCHAR2(255 CHAR),
    "Deutsch" VARCHAR2(255 CHAR),
    "Francais" VARCHAR2(255 CHAR),
    "ID" NUMBER NOT NULL ENABLE,
    "Italiano" VARCHAR2(255 CHAR),
    "Japanese" VARCHAR2(255 CHAR),
    "Nederlands" VARCHAR2(255 CHAR),
    "Pictogram" VARCHAR2(255 CHAR),
    "Polski" VARCHAR2(255 CHAR),
    "Russian" VARCHAR2(255 CHAR),
    "Swedish" VARCHAR2(255 CHAR),
    "Turkish" VARCHAR2(255 CHAR),
    "Portugues" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."Layer" (
    "EntryID" NUMBER NOT NULL ENABLE,
    "LayerName" VARCHAR2(20 CHAR),
    PRIMARY KEY ("EntryID") ENABLE
);

CREATE TABLE "E3_ADMIN"."LOCKINFO" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE,
    "TYPE" NUMBER NOT NULL ENABLE,
    "USER" VARCHAR2(255 CHAR),
    "HOST" VARCHAR2(255 CHAR),
    "PID" NUMBER,
    "TIME" NUMBER,
    PRIMARY KEY ("ENTRY", "VERSION", "TYPE") ENABLE
);

CREATE TABLE "E3_ADMIN"."LogicAttribute" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "GateNumber" NUMBER NOT NULL ENABLE,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER NOT NULL ENABLE,
    "AttributeValue" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ENTRY", "GateNumber", "AttributeName", "Copy") ENABLE
);

CREATE TABLE "E3_ADMIN"."MATERIAL" (
    "ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "RESISTIVITY_TEMP" FLOAT(126),
    "THERMAL_CAP" FLOAT(126),
    "GRAVITY" FLOAT(126),
    "RESISTANCE" FLOAT(126),
    "SPECIFIC_RESISTANCE" FLOAT(126),
    PRIMARY KEY ("ID", "NAME") ENABLE
);

CREATE TABLE "E3_ADMIN"."ModelAttribute" (
    "ID" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER NOT NULL ENABLE,
    "AttributeValue" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID", "Entry", "AttributeName", "Copy") ENABLE
);

CREATE TABLE "E3_ADMIN"."ModelData" (
    "ID" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "Entry" VARCHAR2(255 CHAR),
    "Type" NUMBER,
    "Class" VARCHAR2(80 CHAR),
    "Description" VARCHAR2(255 CHAR),
    "LASTUPDT" DATE,
    "DATEMAIN" DATE,
    "*Owner" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."OUTDATED" (
    "ID" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."Outlines" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "OutlineNumber" NUMBER NOT NULL ENABLE,
    "Type" NUMBER,
    "X" FLOAT(126),
    "Y" FLOAT(126),
    "Z" FLOAT(126),
    "LineY" FLOAT(126),
    "LineZ" FLOAT(126),
    "AreaZ" FLOAT(126),
    "Height" FLOAT(126),
    "OutlineData" BLOB,
    "RestrictedLayer" NUMBER,
    "DescriptionLevel" NUMBER,
    "Flags" NUMBER,
    PRIMARY KEY ("Entry", "OutlineNumber") ENABLE
);

CREATE TABLE "E3_ADMIN"."OutlineSymbols" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "OutlineNumber" NUMBER NOT NULL ENABLE,
    "ViewNumber" NUMBER NOT NULL ENABLE,
    "Symbol" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    PRIMARY KEY ("Entry", "OutlineNumber", "ViewNumber", "Symbol") ENABLE
);

CREATE TABLE "E3_ADMIN"."PadStack" (
    "EntryID" NUMBER NOT NULL ENABLE,
    "PadSym" VARCHAR2(20 CHAR),
    "LayerID" NUMBER NOT NULL ENABLE,
    "Flags" NUMBER,
    PRIMARY KEY ("EntryID", "LayerID") ENABLE
);

CREATE TABLE "E3_ADMIN"."PenDefinition" (
    "Type" NUMBER NOT NULL ENABLE,
    "ColorIndex" NUMBER,
    "PenStyle" NUMBER,
    "PenWidth" FLOAT(126),
    PRIMARY KEY ("Type") ENABLE
);

CREATE TABLE "E3_ADMIN"."PhysPin" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "PinNumber" NUMBER NOT NULL ENABLE,
    "ConnX" FLOAT(126),
    "ConnY" FLOAT(126),
    "ConnZ" FLOAT(126),
    "ConnType" NUMBER,
    "ConnDirection" NUMBER,
    "WireColor" NUMBER,
    "ConnDimension1" FLOAT(126),
    "ConnDimension2" FLOAT(126),
    "AWGMin" FLOAT(126),
    "AWGMax" FLOAT(126),
    "ConnDimensionMax" FLOAT(126),
    "WireMax" NUMBER,
    "SpineX" FLOAT(126),
    "SpineY" FLOAT(126),
    "SpineZ" FLOAT(126),
    "SlopeAngle" FLOAT(126),
    "PluggableDepth" FLOAT(126),
    "PinCode" NUMBER,
    "PinLayer" NUMBER,
    "PinRotation" FLOAT(126),
    "TestPointCode" NUMBER,
    "TechStackS" VARCHAR2(20 CHAR),
    "TechStackC" VARCHAR2(20 CHAR),
    "DrillID" NUMBER,
    "Flags2" NUMBER,
    PRIMARY KEY ("Entry", "PinNumber") ENABLE
);

CREATE TABLE "E3_ADMIN"."Pin" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "PHYSPIN" VARCHAR2(64 CHAR),
    "FUNCT" NUMBER,
    "PINEQUIV" NUMBER,
    "LPINEQV" NUMBER,
    "PINNAME" VARCHAR2(200 CHAR),
    "NPINEQV" NUMBER,
    "Flags" NUMBER,
    "TPNPRIO" NUMBER,
    "FLAGS2" NUMBER,
    PRIMARY KEY ("ENTRY", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."PinAttribute" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "PinNumber" NUMBER NOT NULL ENABLE,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER NOT NULL ENABLE,
    "AttributeValue" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ENTRY", "PinNumber", "AttributeName", "Copy") ENABLE
);

CREATE TABLE "E3_ADMIN"."PinDesign" (
    "Entry" VARCHAR2(20 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER,
    "TechnologyID" NUMBER NOT NULL ENABLE,
    "PadStackID" NUMBER,
    PRIMARY KEY ("Entry", "TechnologyID") ENABLE
);

CREATE TABLE "E3_ADMIN"."PlugInfo" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "PINCOMP" VARCHAR2(255 CHAR),
    "ActiveCounterPart" NUMBER(1, 0),
    "PINPART" VARCHAR2(255 CHAR),
    "ActiveFittingPart" NUMBER(1, 0),
    "PinNumber" NUMBER,
    "ActiveWireSeal" NUMBER(1, 0),
    PRIMARY KEY ("ENTRY", "VERSION", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."RetainingRailTypes" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "Type" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("Entry", "Type") ENABLE
);

CREATE TABLE "E3_ADMIN"."SchematicTypes" (
    "Type" NUMBER NOT NULL ENABLE,
    "IconUnplaced" BLOB,
    "IconPlaced" BLOB,
    "IconInactive" BLOB,
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR),
    PRIMARY KEY ("Type") ENABLE
);

CREATE TABLE "E3_ADMIN"."SETTINGS" (
    "PARAM" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "VALUE" VARCHAR2(255 CHAR),
    PRIMARY KEY ("PARAM") ENABLE
);

CREATE TABLE "E3_ADMIN"."SheetInformation" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "SheetType" NUMBER,
    "LayoutType" NUMBER,
    "HorzLayout" BLOB,
    "VertLayout" BLOB,
    "Orientation" VARCHAR2(12 CHAR),
    "DrawingArea" BLOB,
    "PRINT_AREA" BLOB,
    PRIMARY KEY ("ENTRY") ENABLE
);

CREATE TABLE "E3_ADMIN"."SlotAttribute" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "SlotNumber" NUMBER NOT NULL ENABLE,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER NOT NULL ENABLE,
    "AttributeValue" VARCHAR2(255 CHAR),
    PRIMARY KEY ("Entry", "SlotNumber", "AttributeName", "Copy") ENABLE
);

CREATE TABLE "E3_ADMIN"."Slots" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER NOT NULL ENABLE,
    "Type" NUMBER,
    "RetainingRailType" NUMBER,
    "x1" FLOAT(126),
    "y1" FLOAT(126),
    "z1" FLOAT(126),
    "x2" FLOAT(126),
    "y2" FLOAT(126),
    "z2" FLOAT(126),
    "Width" FLOAT(126),
    PRIMARY KEY ("Entry", "Copy") ENABLE
);

CREATE TABLE "E3_ADMIN"."Supply" (
    "ENTRY" VARCHAR2(20 CHAR) NOT NULL ENABLE,
    "Potentialnummer" NUMBER NOT NULL ENABLE,
    "Potentialname" VARCHAR2(20 CHAR),
    PRIMARY KEY ("ENTRY", "Potentialnummer") ENABLE
);

CREATE TABLE "E3_ADMIN"."SymbolAttribute" (
    "ID" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE,
    "Copy" NUMBER NOT NULL ENABLE,
    "AttributeValue" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID", "ENTRY", "VERSION", "AttributeName", "Copy") ENABLE
);

CREATE TABLE "E3_ADMIN"."SymbolData" (
    "ID" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "ENTRY" VARCHAR2(255 CHAR),
    "VERSION" VARCHAR2(4 CHAR),
    "Norm" NUMBER,
    "LSHDES" VARCHAR2(4 CHAR),
    "LSHTYP" NUMBER,
    "ENTRYTYP" NUMBER,
    "LPNTR" VARCHAR2(255 CHAR),
    "VSTATUS" VARCHAR2(1 CHAR),
    "VersionText" VARCHAR2(80 CHAR),
    "DATEMAIN" DATE,
    "LASTUPDT" DATE,
    "Class" VARCHAR2(80 CHAR),
    "Description" VARCHAR2(255 CHAR),
    "SYMINDEX" NUMBER,
    "FLAGS2" NUMBER,
    "FLAGS" NUMBER,
    "SUBTYP" NUMBER,
    "*Owner" VARCHAR2(255 CHAR),
    "*Normative_doc" VARCHAR2(255 CHAR),
    "Class-main" VARCHAR2(80 CHAR),
    PRIMARY KEY ("ID") ENABLE
);

CREATE TABLE "E3_ADMIN"."SymbolDimension" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "LSHX1" FLOAT(126),
    "LSHY1" FLOAT(126),
    "LSHX2" FLOAT(126),
    "LSHY2" FLOAT(126),
    PRIMARY KEY ("ENTRY") ENABLE
);

CREATE TABLE "E3_ADMIN"."SYMBOL_FUNCTION" (
    "LPNTR" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "LBNNUM" NUMBER NOT NULL ENABLE,
    "FUSUBID" NUMBER NOT NULL ENABLE,
    "FUNAME" VARCHAR2(255 CHAR),
    "FUID" NUMBER,
    "FUPORT" NUMBER,
    PRIMARY KEY ("LPNTR", "LBNNUM", "FUSUBID") ENABLE
);

CREATE TABLE "E3_ADMIN"."SymbolGraphic" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "GraphicType" NUMBER,
    "Linecolor" NUMBER,
    "Linetype" NUMBER,
    "Linewidth" FLOAT(126),
    "Fillmode" NUMBER,
    "Fillcolor" NUMBER,
    "HatchData" BLOB,
    "GraphicData" BLOB,
    "GraphicLevel" NUMBER,
    "Flags" NUMBER,
    "ID" NUMBER,
    "STATE_ID" VARCHAR2(36 CHAR),
    PRIMARY KEY ("ENTRY", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."SymbolNodes" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "LIBNTY" NUMBER,
    "LIBNX" FLOAT(126),
    "LIBNY" FLOAT(126),
    "LBSTUB" NUMBER,
    "LBNNUM" NUMBER,
    "Function" NUMBER,
    PRIMARY KEY ("ENTRY", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."SymbolPoints" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "FLAGS" NUMBER,
    "POSX" FLOAT(126),
    "POSY" FLOAT(126),
    PRIMARY KEY ("ENTRY", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."SYMBOL_STATES" (
    "ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "NAME" VARCHAR2(255 CHAR),
    "SYMBOL_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "FU_STATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "FUSUBID" NUMBER NOT NULL ENABLE,
    "ORDER_NUM" NUMBER,
    "FLAGS" NUMBER,
    PRIMARY KEY ("ID", "SYMBOL_ID", "FU_STATE_ID", "FUSUBID") ENABLE
);

CREATE TABLE "E3_ADMIN"."SymbolText" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COPY" NUMBER NOT NULL ENABLE,
    "TTYPE" NUMBER,
    "TX" FLOAT(126),
    "TY" FLOAT(126),
    "TJUST" NUMBER,
    "THT" FLOAT(126),
    "TMOD" NUMBER,
    "TLEV" NUMBER,
    "TSTR" VARCHAR2(255 CHAR),
    "LBNNUM" NUMBER,
    "Flags" NUMBER,
    "TROT" FLOAT(126),
    "FontName" VARCHAR2(255 CHAR),
    "FontStyle" NUMBER,
    "TextColor" NUMBER,
    "Flags2" NUMBER,
    "SIZEX" FLOAT(126),
    "SIZEY" FLOAT(126),
    "Hyperlink" VARCHAR2(255 CHAR),
    "SOURCE" NUMBER,
    PRIMARY KEY ("ENTRY", "COPY") ENABLE
);

CREATE TABLE "E3_ADMIN"."Technology" (
    "EntryID" NUMBER NOT NULL ENABLE,
    "Description" VARCHAR2(20 CHAR) NOT NULL ENABLE,
    PRIMARY KEY ("EntryID", "Description") ENABLE
);

CREATE TABLE "E3_ADMIN"."TextInformation" (
    "TextType" NUMBER NOT NULL ENABLE,
    "MaxLength" NUMBER,
    "Format" VARCHAR2(80 CHAR),
    "SheetInfo" NUMBER(1, 0),
    "CopyFromSelectedSheet" NUMBER(1, 0),
    "ChangeableByScriptOnly" NUMBER(1, 0),
    "CanModify" NUMBER(1, 0),
    "CanHide" NUMBER(1, 0),
    "CanModifyInivisible" NUMBER(1, 0),
    "DatabaseField" VARCHAR2(255 CHAR),
    "SystemDefined" NUMBER(1, 0),
    "ConnectionTargetFormat" NUMBER(1, 0),
    "UseActivePinTerminal" NUMBER(1, 0),
    "TEXTNAME_86" VARCHAR2(255 CHAR),
    "TEXTNAME_31" VARCHAR2(255 CHAR),
    "TEXTNAME_44" VARCHAR2(255 CHAR),
    "TEXTNAME_33" VARCHAR2(255 CHAR),
    "TEXTNAME_49" VARCHAR2(255 CHAR),
    "TEXTNAME_39" VARCHAR2(255 CHAR),
    "TEXTNAME_81" VARCHAR2(255 CHAR),
    "TEXTNAME_351" VARCHAR2(255 CHAR),
    "TEXTNAME_07" VARCHAR2(255 CHAR),
    "TEXTNAME_34" VARCHAR2(255 CHAR),
    "TEXTNAME_90" VARCHAR2(255 CHAR),
    "TEXTNAME_48" VARCHAR2(255 CHAR),
    PRIMARY KEY ("TextType") ENABLE
);

CREATE TABLE "E3_ADMIN"."TwistedPairs" (
    "CrossSection" FLOAT(126) NOT NULL ENABLE,
    "OuterDiameter" FLOAT(126) NOT NULL ENABLE,
    "NumberOfWires" NUMBER NOT NULL ENABLE,
    "NumberOfTurns" NUMBER,
    "TwistedLengthFactor" FLOAT(126) NOT NULL ENABLE,
    PRIMARY KEY ("CrossSection", "OuterDiameter", "NumberOfWires", "TwistedLengthFactor") ENABLE
);

CREATE TABLE "E3_ADMIN"."ValidRetainingRailTypes" (
    "Type" NUMBER NOT NULL ENABLE,
    "Description" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    PRIMARY KEY ("Type", "Description") ENABLE
);

CREATE TABLE "E3_ADMIN"."WireColorCodes" (
    "ColorCode" NUMBER NOT NULL ENABLE,
    "Color" NUMBER,
    "Linetype" NUMBER,
    "Type" NUMBER,
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ColorCode") ENABLE
);

CREATE TABLE "E3_ADMIN"."WIREKIND" (
    "ID" NUMBER NOT NULL ENABLE,
    "MATID1" NUMBER NOT NULL ENABLE,
    "MATID2" NUMBER,
    "ALLOW_TEMP" FLOAT(126),
    "MELTING_TEMP" FLOAT(126),
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID", "MATID1") ENABLE
);

CREATE TABLE "E3_ADMIN"."WIRESIZE" (
    "CROSSEC" FLOAT(126) NOT NULL ENABLE,
    "MATID" NUMBER NOT NULL ENABLE,
    "RESISTANCE" FLOAT(126),
    "INNER_DIA" FLOAT(126),
    "OUTER_DIA" FLOAT(126) NOT NULL ENABLE,
    PRIMARY KEY ("CROSSEC", "MATID", "OUTER_DIA") ENABLE
);

