-- Скрипт для воссоздания схемы E3_ADMIN
-- Сгенерировано: 2025-09-25 12:00:38

CREATE TABLE "Assembly" (
    "LPNTR" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "FLAGS" NUMBER,
    "NAME" VARCHAR2(80 CHAR),
    "SUBENTRY" VARCHAR2(255 CHAR),
    "SUBVERSION" VARCHAR2(4 CHAR)
);

CREATE TABLE "AttributeDefinition" (
    "AttributeID" NUMBER,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL,
    "Typ" NUMBER,
    "Owner" NUMBER,
    "Owner2" NUMBER,
    "SingleInstance" NUMBER(1, 0),
    "MustExist" NUMBER(1, 0),
    "Hidden" NUMBER(1, 0),
    "Format" VARCHAR2(80 CHAR),
    "PositionX" FLOAT(126),
    "PositionY" FLOAT(126),
    "Visible" NUMBER,
    "Color" NUMBER,
    "Ratio" NUMBER,
    "Size" FLOAT(126),
    "Direction" NUMBER,
    "Level" NUMBER,
    "DefaultValue" VARCHAR2(255 CHAR),
    "ASSIGNED_LIST" VARCHAR2(255 CHAR),
    "UNIQUE_VALUE" NUMBER,
    "Flags2" NUMBER,
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR),
    "USAGE_DESCRIPTION" VARCHAR2(50 CHAR)
);

CREATE TABLE "ATTRIBUTE_LISTS" (
    "ID" NUMBER NOT NULL,
    "ASSIGNED_LIST" VARCHAR2(255 CHAR),
    "READ_ONLY" NUMBER(1, 0),
    "LOWER" FLOAT(126),
    "UPPER" FLOAT(126)
);

CREATE TABLE "ATTRIBUTE_LIST_VALUES" (
    "ID" NUMBER NOT NULL,
    "COPY" NUMBER NOT NULL,
    "VALUE" VARCHAR2(255 CHAR)
);

CREATE TABLE "BlockedInfos" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL,
    "RootEntry" VARCHAR2(255 CHAR) NOT NULL,
    "BlockedPins" BLOB
);

CREATE TABLE "Cable" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "BundleID" NUMBER,
    "ParentID" NUMBER,
    "Name" VARCHAR2(64 CHAR),
    "NODENO" NUMBER,
    "CrossSection" FLOAT(126),
    "Color" NUMBER,
    "Flags" NUMBER,
    "SUBENTRY" VARCHAR2(255 CHAR),
    "SUBVERSION" VARCHAR2(4 CHAR),
    "OuterDia" FLOAT(126)
);

CREATE TABLE "ColumnDescription" (
    "TableName" VARCHAR2(128 CHAR) NOT NULL,
    "ColumnName" VARCHAR2(128 CHAR) NOT NULL,
    "English" VARCHAR2(80 CHAR),
    "German" VARCHAR2(80 CHAR),
    "French" VARCHAR2(80 CHAR),
    "Chinese" VARCHAR2(80 CHAR),
    "Dutch" VARCHAR2(80 CHAR),
    "Italian" VARCHAR2(80 CHAR),
    "Japanese" VARCHAR2(80 CHAR),
    "Polski" VARCHAR2(255 CHAR),
    "Portuguese" VARCHAR2(80 CHAR),
    "Russian" VARCHAR2(80 CHAR),
    "Spanish" VARCHAR2(80 CHAR),
    "Turkish" VARCHAR2(80 CHAR)
);

CREATE TABLE "ComponentAttribute" (
    "ID" VARCHAR2(40 CHAR) NOT NULL,
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL,
    "BundleID" NUMBER NOT NULL,
    "NODENO" NUMBER NOT NULL,
    "Flags" NUMBER NOT NULL,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL,
    "Copy" NUMBER NOT NULL,
    "AttributeValue" VARCHAR2(255 CHAR)
);

CREATE TABLE "ComponentClassification" (
    "Name" VARCHAR2(255 CHAR) NOT NULL,
    "Structure" BLOB
);

CREATE TABLE "ComponentData" (
    "ID" VARCHAR2(40 CHAR) NOT NULL,
    "ENTRY" VARCHAR2(255 CHAR),
    "VERSION" VARCHAR2(4 CHAR),
    "DeviceLetterCode" VARCHAR2(4 CHAR),
    "Class" VARCHAR2(80 CHAR),
    "ENTRYTYP" NUMBER,
    "Description" VARCHAR2(255 CHAR),
    "LPNTR" VARCHAR2(255 CHAR),
    "VSTATUS" VARCHAR2(1 CHAR),
    "VersionText" VARCHAR2(80 CHAR),
    "DATEMAIN" DATE,
    "LASTUPDT" DATE,
    "MPNTR" VARCHAR2(255 CHAR),
    "Flags" NUMBER,
    "ArticleNumber" VARCHAR2(80 CHAR),
    "Supplier" VARCHAR2(80 CHAR),
    "SPNTR" VARCHAR2(20 CHAR),
    "SUBTYP" NUMBER,
    "*Normative_doc" VARCHAR2(255 CHAR),
    "*Owner" VARCHAR2(80 CHAR),
    "*SAP_nomer" VARCHAR2(128 CHAR),
    "Class-main" VARCHAR2(80 CHAR),
    "TC_ID" VARCHAR2(128 CHAR)
);

CREATE TABLE "COMPONENT_STATES" (
    "ID" VARCHAR2(36 CHAR) NOT NULL,
    "NAME" VARCHAR2(255 CHAR),
    "COMP_ID" VARCHAR2(36 CHAR) NOT NULL,
    "SYMBOL_STATE_ID" VARCHAR2(36 CHAR) NOT NULL,
    "GATNUM" NUMBER NOT NULL,
    "ORDER_NUM" NUMBER
);

CREATE TABLE "ConnectionTypes" (
    "ConnectionType" NUMBER NOT NULL,
    "Flags" NUMBER,
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR)
);

CREATE TABLE "CR_ATTRIBUTES" (
    "CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL,
    "NAME" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "VALUE" VARCHAR2(255 CHAR)
);

CREATE TABLE "CRIMPING_RULES" (
    "GUID" VARCHAR2(36 CHAR) NOT NULL,
    "PHSYPIN_ENTRY" VARCHAR2(255 CHAR),
    "PHYSPIN_PIN_NUMBER" NUMBER,
    "RULE_ID" NUMBER,
    "DESCRIPTION" VARCHAR2(255 CHAR),
    "RULE_TYPE" NUMBER
);

CREATE TABLE "CrossSections" (
    "ID" NUMBER NOT NULL,
    "CrossSection" FLOAT(126) NOT NULL,
    "Description" VARCHAR2(255 CHAR),
    "Flags" NUMBER,
    "Type" NUMBER
);

CREATE TABLE "CR_WIRE_DEFINITION_ATTRIBUTES" (
    "CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL,
    "CR_WIRE_DEFINITIONS_INDEX" NUMBER NOT NULL,
    "NAME" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "VALUE" VARCHAR2(255 CHAR),
    "RANGE_MAX" VARCHAR2(255 CHAR),
    "FLAGS" NUMBER
);

CREATE TABLE "CR_WIRE_DEFINITIONS" (
    "CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL,
    "INDEX" NUMBER NOT NULL,
    "MIN_SIZE" FLOAT(126),
    "MAX_SIZE" FLOAT(126)
);

CREATE TABLE "DatabaseInfo" (
    "Version" VARCHAR2(10 CHAR) NOT NULL,
    "Description" VARCHAR2(255 CHAR)
);

CREATE TABLE "DatabaseTree" (
    "Structure" VARCHAR2(255 CHAR) NOT NULL,
    "Data" BLOB,
    "TreeType" NUMBER NOT NULL,
    "Active" NUMBER(1, 0)
);

CREATE TABLE "Drill" (
    "EntryID" NUMBER NOT NULL,
    "Diameter" FLOAT(126),
    "Tolerance" FLOAT(126),
    "Unit" VARCHAR2(20 CHAR),
    "Type" NUMBER,
    "TData" BLOB
);

CREATE TABLE "ELECTRICAL_ATTRIBUTES" (
    "WIREKIND_ID" NUMBER NOT NULL,
    "RELATIVE_PERMITTIVITY" FLOAT(126),
    "LOSS_ANGLE" FLOAT(126)
);


CREATE TABLE "FAVORITES" (
    "ID" NUMBER NOT NULL,
    "NAME" VARCHAR2(255 CHAR),
    "TYPE" NUMBER,
    "SEQUENCE" NUMBER
);

CREATE TABLE "FAVORITE_VALUES" (
    "ID" NUMBER NOT NULL,
    "COPY" NUMBER NOT NULL,
    "DBFIELD" VARCHAR2(255 CHAR),
    "DESCRIPTION" VARCHAR2(255 CHAR),
    "VALUE" VARCHAR2(255 CHAR),
    "FLAGS" NUMBER
);

CREATE TABLE "FUNCTIONAL_ASSIGNMENTS" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL,
    "NAME" VARCHAR2(255 CHAR) NOT NULL,
    "PINCOPY" NUMBER NOT NULL,
    "FUNAME" VARCHAR2(255 CHAR),
    "FUID" NUMBER,
    "FUPORT" NUMBER
);

CREATE TABLE "FUNCTIONAL_PORTS" (
    "NAME" VARCHAR2(255 CHAR) NOT NULL,
    "ID" NUMBER NOT NULL,
    "COPY" NUMBER NOT NULL,
    "PORT" VARCHAR2(255 CHAR),
    "FLAGS" NUMBER
);

CREATE TABLE "FUNCTIONAL_UNITS" (
    "NAME" VARCHAR2(255 CHAR) NOT NULL,
    "ID" NUMBER NOT NULL,
    "SYMBOL" VARCHAR2(255 CHAR),
    "TYPE" NUMBER
);

CREATE TABLE "FUNCTIONAL_UNIT_STATES" (
    "ID" VARCHAR2(36 CHAR) NOT NULL,
    "NAME" VARCHAR2(255 CHAR),
    "FU_NAME" VARCHAR2(255 CHAR) NOT NULL,
    "FU_ID" NUMBER NOT NULL,
    "ORDER_NUM" NUMBER,
    "FLAGS" NUMBER
);

CREATE TABLE "FUNCTION_ATTRIBUTES" (
    "NAME" VARCHAR2(255 CHAR) NOT NULL,
    "ID" NUMBER NOT NULL,
    "PORT_NUMBER" NUMBER NOT NULL,
    "ATTRIBUTE_NAME" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "STATE_ID" VARCHAR2(36 CHAR) NOT NULL,
    "ATTRIBUTE_VALUE" VARCHAR2(255 CHAR)
);

CREATE TABLE "Gate" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "CCTNAME" VARCHAR2(255 CHAR)
);

CREATE TABLE "GATE_FUNCTION_ATTRIBUTES" (
    "LPNTR" VARCHAR2(255 CHAR) NOT NULL,
    "GateNumber" NUMBER NOT NULL,
    "FUSUBID" NUMBER NOT NULL,
    "STATE_ID" VARCHAR2(36 CHAR) NOT NULL,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL,
    "Copy" NUMBER NOT NULL,
    "AttributeValue" VARCHAR2(255 CHAR)
);

CREATE TABLE "GatePinRelation" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "GateNumber" NUMBER NOT NULL,
    "PinNumber" NUMBER NOT NULL,
    "Representation" NUMBER NOT NULL,
    "NodeNumber" NUMBER NOT NULL
);

CREATE TABLE "IEC 750 letter codes" (
    "ID" NUMBER NOT NULL,
    "LetterCode" VARCHAR2(255 CHAR),
    "ValueRange" VARCHAR2(255 CHAR),
    "Class" VARCHAR2(255 CHAR),
    "Klasse" VARCHAR2(255 CHAR),
    "Classe" VARCHAR2(255 CHAR),
    "Clase" VARCHAR2(255 CHAR),
    "Eeann" VARCHAR2(256 CHAR)
);

CREATE TABLE "Languages" (
    "<mainClass>" VARCHAR2(255 CHAR),
    "<subClass>" VARCHAR2(255 CHAR),
    "American English" VARCHAR2(255 CHAR),
    "British English" VARCHAR2(255 CHAR),
    "Castellano" VARCHAR2(255 CHAR),
    "Chinese" VARCHAR2(255 CHAR),
    "Chinese(CHT)" VARCHAR2(255 CHAR),
    "Description" VARCHAR2(255 CHAR),
    "Deutsch" VARCHAR2(255 CHAR),
    "Francais" VARCHAR2(255 CHAR),
    "ID" NUMBER NOT NULL,
    "Italiano" VARCHAR2(255 CHAR),
    "Japanese" VARCHAR2(255 CHAR),
    "Nederlands" VARCHAR2(255 CHAR),
    "Pictogram" VARCHAR2(255 CHAR),
    "Polski" VARCHAR2(255 CHAR),
    "Russian" VARCHAR2(255 CHAR),
    "Swedish" VARCHAR2(255 CHAR),
    "Turkish" VARCHAR2(255 CHAR),
    "Portugues" VARCHAR2(255 CHAR)
);

CREATE TABLE "Layer" (
    "EntryID" NUMBER NOT NULL,
    "LayerName" VARCHAR2(20 CHAR)
);

CREATE TABLE "LOCKINFO" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL,
    "TYPE" NUMBER NOT NULL,
    "USER" VARCHAR2(255 CHAR),
    "HOST" VARCHAR2(255 CHAR),
    "PID" NUMBER,
    "TIME" NUMBER
);

CREATE TABLE "LogicAttribute" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "GateNumber" NUMBER NOT NULL,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL,
    "Copy" NUMBER NOT NULL,
    "AttributeValue" VARCHAR2(255 CHAR)
);

CREATE TABLE "MATERIAL" (
    "ID" NUMBER NOT NULL,
    "NAME" VARCHAR2(255 CHAR) NOT NULL,
    "RESISTIVITY_TEMP" FLOAT(126),
    "THERMAL_CAP" FLOAT(126),
    "GRAVITY" FLOAT(126),
    "RESISTANCE" FLOAT(126),
    "SPECIFIC_RESISTANCE" FLOAT(126)
);

CREATE TABLE "ModelAttribute" (
    "ID" VARCHAR2(40 CHAR) NOT NULL,
    "Entry" VARCHAR2(255 CHAR) NOT NULL,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL,
    "Copy" NUMBER NOT NULL,
    "AttributeValue" VARCHAR2(255 CHAR)
);

CREATE TABLE "ModelData" (
    "ID" VARCHAR2(40 CHAR) NOT NULL,
    "Entry" VARCHAR2(255 CHAR),
    "Type" NUMBER,
    "Class" VARCHAR2(80 CHAR),
    "Description" VARCHAR2(255 CHAR),
    "LASTUPDT" DATE,
    "DATEMAIN" DATE,
    "*Owner" VARCHAR2(255 CHAR)
);

CREATE TABLE "OUTDATED" (
    "ID" NUMBER NOT NULL
);

CREATE TABLE "Outlines" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL,
    "OutlineNumber" NUMBER NOT NULL,
    "Type" NUMBER,
    "X" FLOAT(126),
    "Y" FLOAT(126),
    "Z" FLOAT(126),
    "LineY" FLOAT(126),
    "LineZ" FLOAT(126),
    "AreaZ" FLOAT(126),
    "Height" FLOAT(126),
    "OutlineData" BLOB,
    "RestrictedLayer" NUMBER,
    "DescriptionLevel" NUMBER,
    "Flags" NUMBER
);

CREATE TABLE "OutlineSymbols" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL,
    "OutlineNumber" NUMBER NOT NULL,
    "ViewNumber" NUMBER NOT NULL,
    "Symbol" VARCHAR2(255 CHAR) NOT NULL
);

CREATE TABLE "PadStack" (
    "EntryID" NUMBER NOT NULL,
    "PadSym" VARCHAR2(20 CHAR),
    "LayerID" NUMBER NOT NULL,
    "Flags" NUMBER
);

CREATE TABLE "PenDefinition" (
    "Type" NUMBER NOT NULL,
    "ColorIndex" NUMBER,
    "PenStyle" NUMBER,
    "PenWidth" FLOAT(126)
);

CREATE TABLE "PhysPin" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL,
    "PinNumber" NUMBER NOT NULL,
    "ConnX" FLOAT(126),
    "ConnY" FLOAT(126),
    "ConnZ" FLOAT(126),
    "ConnType" NUMBER,
    "ConnDirection" NUMBER,
    "WireColor" NUMBER,
    "ConnDimension1" FLOAT(126),
    "ConnDimension2" FLOAT(126),
    "AWGMin" FLOAT(126),
    "AWGMax" FLOAT(126),
    "ConnDimensionMax" FLOAT(126),
    "WireMax" NUMBER,
    "SpineX" FLOAT(126),
    "SpineY" FLOAT(126),
    "SpineZ" FLOAT(126),
    "SlopeAngle" FLOAT(126),
    "PluggableDepth" FLOAT(126),
    "PinCode" NUMBER,
    "PinLayer" NUMBER,
    "PinRotation" FLOAT(126),
    "TestPointCode" NUMBER,
    "TechStackS" VARCHAR2(20 CHAR),
    "TechStackC" VARCHAR2(20 CHAR),
    "DrillID" NUMBER,
    "Flags2" NUMBER
);

CREATE TABLE "Pin" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "PHYSPIN" VARCHAR2(64 CHAR),
    "FUNCT" NUMBER,
    "PINEQUIV" NUMBER,
    "LPINEQV" NUMBER,
    "PINNAME" VARCHAR2(200 CHAR),
    "NPINEQV" NUMBER,
    "Flags" NUMBER,
    "TPNPRIO" NUMBER,
    "FLAGS2" NUMBER
);

CREATE TABLE "PinAttribute" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "PinNumber" NUMBER NOT NULL,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL,
    "Copy" NUMBER NOT NULL,
    "AttributeValue" VARCHAR2(255 CHAR)
);

CREATE TABLE "PinDesign" (
    "Entry" VARCHAR2(20 CHAR) NOT NULL,
    "Copy" NUMBER,
    "TechnologyID" NUMBER NOT NULL,
    "PadStackID" NUMBER
);

CREATE TABLE "PlugInfo" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "PINCOMP" VARCHAR2(255 CHAR),
    "ActiveCounterPart" NUMBER(1, 0),
    "PINPART" VARCHAR2(255 CHAR),
    "ActiveFittingPart" NUMBER(1, 0),
    "PinNumber" NUMBER,
    "ActiveWireSeal" NUMBER(1, 0)
);

CREATE TABLE "RetainingRailTypes" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL,
    "Type" NUMBER NOT NULL
);

CREATE TABLE "SchematicTypes" (
    "Type" NUMBER NOT NULL,
    "IconUnplaced" BLOB,
    "IconPlaced" BLOB,
    "IconInactive" BLOB,
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR)
);

CREATE TABLE "SETTINGS" (
    "PARAM" VARCHAR2(255 CHAR) NOT NULL,
    "VALUE" VARCHAR2(255 CHAR)
);

CREATE TABLE "SheetInformation" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "SheetType" NUMBER,
    "LayoutType" NUMBER,
    "HorzLayout" BLOB,
    "VertLayout" BLOB,
    "Orientation" VARCHAR2(12 CHAR),
    "DrawingArea" BLOB,
    "PRINT_AREA" BLOB -- РЕКОМЕНДУЕМОЕ ИЗМЕНЕНИЕ
);

CREATE TABLE "SlotAttribute" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL,
    "SlotNumber" NUMBER NOT NULL,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL,
    "Copy" NUMBER NOT NULL,
    "AttributeValue" VARCHAR2(255 CHAR)
);

CREATE TABLE "Slots" (
    "Entry" VARCHAR2(255 CHAR) NOT NULL,
    "Copy" NUMBER NOT NULL,
    "Type" NUMBER,
    "RetainingRailType" NUMBER,
    "x1" FLOAT(126),
    "y1" FLOAT(126),
    "z1" FLOAT(126),
    "x2" FLOAT(126),
    "y2" FLOAT(126),
    "z2" FLOAT(126),
    "Width" FLOAT(126)
);

CREATE TABLE "Supply" (
    "ENTRY" VARCHAR2(20 CHAR) NOT NULL,
    "Potentialnummer" NUMBER NOT NULL,
    "Potentialname" VARCHAR2(20 CHAR)
);

CREATE TABLE "SymbolAttribute" (
    "ID" VARCHAR2(40 CHAR) NOT NULL,
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "VERSION" VARCHAR2(4 CHAR) NOT NULL,
    "AttributeName" VARCHAR2(80 CHAR) NOT NULL,
    "Copy" NUMBER NOT NULL,
    "AttributeValue" VARCHAR2(255 CHAR)
);

CREATE TABLE "SymbolData" (
    "ID" VARCHAR2(40 CHAR) NOT NULL,
    "ENTRY" VARCHAR2(255 CHAR),
    "VERSION" VARCHAR2(4 CHAR),
    "Norm" NUMBER,
    "LSHDES" VARCHAR2(4 CHAR),
    "LSHTYP" NUMBER,
    "ENTRYTYP" NUMBER,
    "LPNTR" VARCHAR2(255 CHAR),
    "VSTATUS" VARCHAR2(1 CHAR),
    "VersionText" VARCHAR2(80 CHAR),
    "DATEMAIN" DATE,
    "LASTUPDT" DATE,
    "Class" VARCHAR2(80 CHAR),
    "Description" VARCHAR2(255 CHAR),
    "SYMINDEX" NUMBER,
    "FLAGS2" NUMBER,
    "FLAGS" NUMBER,
    "SUBTYP" NUMBER,
    "*Owner" VARCHAR2(255 CHAR),
    "*Normative_doc" VARCHAR2(255 CHAR),
    "Class-main" VARCHAR2(80 CHAR)
);

CREATE TABLE "SymbolDimension" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "LSHX1" FLOAT(126),
    "LSHY1" FLOAT(126),
    "LSHX2" FLOAT(126),
    "LSHY2" FLOAT(126)
);

CREATE TABLE "SYMBOL_FUNCTION" (
    "LPNTR" VARCHAR2(255 CHAR) NOT NULL,
    "LBNNUM" NUMBER NOT NULL,
    "FUSUBID" NUMBER NOT NULL,
    "FUNAME" VARCHAR2(255 CHAR),
    "FUID" NUMBER,
    "FUPORT" NUMBER
);

CREATE TABLE "SymbolGraphic" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "GraphicType" NUMBER,
    "Linecolor" NUMBER,
    "Linetype" NUMBER,
    "Linewidth" FLOAT(126),
    "Fillmode" NUMBER,
    "Fillcolor" NUMBER,
    "HatchData" BLOB, -- РЕКОМЕНДУЕМОЕ ИЗМЕНЕНИЕ
    "GraphicData" BLOB,
    "GraphicLevel" NUMBER,
    "Flags" NUMBER,
    "ID" NUMBER,
    "STATE_ID" VARCHAR2(36 CHAR)
);

CREATE TABLE "SymbolNodes" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "LIBNTY" NUMBER,
    "LIBNX" FLOAT(126),
    "LIBNY" FLOAT(126),
    "LBSTUB" NUMBER,
    "LBNNUM" NUMBER,
    "Function" NUMBER
);

CREATE TABLE "SymbolPoints" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "FLAGS" NUMBER,
    "POSX" FLOAT(126),
    "POSY" FLOAT(126)
);

CREATE TABLE "SYMBOL_STATES" (
    "ID" VARCHAR2(36 CHAR) NOT NULL,
    "NAME" VARCHAR2(255 CHAR),
    "SYMBOL_ID" VARCHAR2(36 CHAR) NOT NULL,
    "FU_STATE_ID" VARCHAR2(36 CHAR) NOT NULL,
    "FUSUBID" NUMBER NOT NULL,
    "ORDER_NUM" NUMBER,
    "FLAGS" NUMBER
);

CREATE TABLE "SymbolText" (
    "ENTRY" VARCHAR2(255 CHAR) NOT NULL,
    "COPY" NUMBER NOT NULL,
    "TTYPE" NUMBER,
    "TX" FLOAT(126),
    "TY" FLOAT(126),
    "TJUST" NUMBER,
    "THT" FLOAT(126),
    "TMOD" NUMBER,
    "TLEV" NUMBER,
    "TSTR" VARCHAR2(255 CHAR),
    "LBNNUM" NUMBER,
    "Flags" NUMBER,
    "TROT" FLOAT(126),
    "FontName" VARCHAR2(255 CHAR),
    "FontStyle" NUMBER,
    "TextColor" NUMBER,
    "Flags2" NUMBER,
    "SIZEX" FLOAT(126),
    "SIZEY" FLOAT(126),
    "Hyperlink" VARCHAR2(255 CHAR),
    "SOURCE" NUMBER
);

CREATE TABLE "Technology" (
    "EntryID" NUMBER NOT NULL,
    "Description" VARCHAR2(20 CHAR) NOT NULL
);

CREATE TABLE "TextInformation" (
    "TextType" NUMBER NOT NULL,
    "MaxLength" NUMBER,
    "Format" VARCHAR2(80 CHAR),
    "SheetInfo" NUMBER(1, 0),
    "CopyFromSelectedSheet" NUMBER(1, 0),
    "ChangeableByScriptOnly" NUMBER(1, 0),
    "CanModify" NUMBER(1, 0),
    "CanHide" NUMBER(1, 0),
    "CanModifyInivisible" NUMBER(1, 0),
    "DatabaseField" VARCHAR2(255 CHAR),
    "SystemDefined" NUMBER(1, 0),
    "ConnectionTargetFormat" NUMBER(1, 0),
    "UseActivePinTerminal" NUMBER(1, 0),
    "TEXTNAME_86" VARCHAR2(255 CHAR),
    "TEXTNAME_31" VARCHAR2(255 CHAR),
    "TEXTNAME_44" VARCHAR2(255 CHAR),
    "TEXTNAME_33" VARCHAR2(255 CHAR),
    "TEXTNAME_49" VARCHAR2(255 CHAR),
    "TEXTNAME_39" VARCHAR2(255 CHAR),
    "TEXTNAME_81" VARCHAR2(255 CHAR),
    "TEXTNAME_351" VARCHAR2(255 CHAR),
    "TEXTNAME_07" VARCHAR2(255 CHAR),
    "TEXTNAME_34" VARCHAR2(255 CHAR),
    "TEXTNAME_90" VARCHAR2(255 CHAR),
    "TEXTNAME_48" VARCHAR2(255 CHAR)
);

CREATE TABLE "TwistedPairs" (
    "CrossSection" FLOAT(126) NOT NULL,
    "OuterDiameter" FLOAT(126) NOT NULL,
    "NumberOfWires" NUMBER NOT NULL,
    "NumberOfTurns" NUMBER,
    "TwistedLengthFactor" FLOAT(126) NOT NULL
);

CREATE TABLE "ValidRetainingRailTypes" (
    "Type" NUMBER NOT NULL,
    "Description" VARCHAR2(255 CHAR) NOT NULL
);

CREATE TABLE "WireColorCodes" (
    "ColorCode" NUMBER NOT NULL,
    "Color" NUMBER,
    "Linetype" NUMBER,
    "Type" NUMBER,
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR)
);

CREATE TABLE "WIREKIND" (
    "ID" NUMBER NOT NULL,
    "MATID1" NUMBER NOT NULL,
    "MATID2" NUMBER,
    "ALLOW_TEMP" FLOAT(126),
    "MELTING_TEMP" FLOAT(126),
    "DESCRIPTION_86" VARCHAR2(255 CHAR),
    "DESCRIPTION_31" VARCHAR2(255 CHAR),
    "DESCRIPTION_44" VARCHAR2(255 CHAR),
    "DESCRIPTION_33" VARCHAR2(255 CHAR),
    "DESCRIPTION_49" VARCHAR2(255 CHAR),
    "DESCRIPTION_39" VARCHAR2(255 CHAR),
    "DESCRIPTION_81" VARCHAR2(255 CHAR),
    "DESCRIPTION_351" VARCHAR2(255 CHAR),
    "DESCRIPTION_07" VARCHAR2(255 CHAR),
    "DESCRIPTION_34" VARCHAR2(255 CHAR),
    "DESCRIPTION_90" VARCHAR2(255 CHAR),
    "DESCRIPTION_48" VARCHAR2(255 CHAR)
);

CREATE TABLE "WIRESIZE" (
    "CROSSEC" FLOAT(126) NOT NULL,
    "MATID" NUMBER NOT NULL,
    "RESISTANCE" FLOAT(126),
    "INNER_DIA" FLOAT(126),
    "OUTER_DIA" FLOAT(126) NOT NULL
);

