# Используем официальный образ Oracle Database 23ai Free
# FROM container-registry.oracle.com/database/free:23.7.0.0-amd64
FROM container-registry.oracle.com/database/free:latest

# Базовые настройки (можно переопределить при docker run)
ENV ORACLE_PDB=FREEPDB1 \
    ORACLE_PWD=MyOracle123 \
    ORACLE_CHARACTERSET=AL32UTF8



COPY ./init_scripts/01-create-user-and-tablespace.sql /opt/oracle/scripts/startup/

