# Используем официальный образ Oracle Database 23ai Free
# FROM container-registry.oracle.com/database/free:23.7.0.0-amd64
FROM container-registry.oracle.com/database/free:latest

# Базовые настройки (можно переопределить при docker run)
ENV ORACLE_PDB=FREEPDB1 \
    ORACLE_PWD=MyOracle123 \
    ORACLE_CHARACTERSET=AL32UTF8

# Копируем ваши скрипты
# Важно: run_scripts.sh кладём в /opt/oracle/scripts/setup — он запустится один раз после создания БД
COPY --chown=oracle:oinstall ./init_scripts/run_scripts.sh                    /opt/oracle/scripts/startup/00-run_scripts.sh
COPY --chown=oracle:oinstall ./init_scripts/01-create-user-and-tablespace.sql /opt/oracle/scripts/custom/01-create-user-and-tablespace.sql
COPY --chown=oracle:oinstall ./init_scripts/02-create-tables.sh               /opt/oracle/scripts/custom/02-create-tables.sh
COPY --chown=oracle:oinstall ./init_scripts/E3_ADMIN_scheme2_fixed.sql        /opt/oracle/scripts/custom/E3_ADMIN_scheme2_fixed.sql

USER root
# Права на выполнение
RUN chmod 755 /opt/oracle/scripts/startup/00-run_scripts.sh \
    && chmod 755 /opt/oracle/scripts/custom/02-create-tables.sh
USER oracle

