-- DROP USER E3_ADMIN;

CREATE TABLE "E3_ADMIN"."ATTRIBUTE_LISTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ASSIGNED_LIST" VARCHAR2(255 CHAR), 
	"READ_ONLY" NUMBER(1,0), 
	"LOWER" FLOAT(126), 
	"UPPER" FLOAT(126), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."ATTRIBUTE_LISTS" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ATTRIBUTE_LISTS" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ATTRIBUTE_LIST_VALUES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"VALUE" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."ATTRIBUTE_LIST_VALUES" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ATTRIBUTE_LIST_VALUES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Assembly" 
   (	"LPNTR" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"FLAGS" NUMBER, 
	"NAME" VARCHAR2(80 CHAR), 
	"SUBENTRY" VARCHAR2(255 CHAR), 
	"SUBVERSION" VARCHAR2(4 CHAR), 
	 PRIMARY KEY ("LPNTR", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Assembly" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."Assembly" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."Assembly" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Assembly" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."Assembly" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."AttributeDefinition" 
   (	"AttributeID" NUMBER, 
	"AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"Typ" NUMBER, 
	"Owner" NUMBER, 
	"Owner2" NUMBER, 
	"SingleInstance" NUMBER(1,0), 
	"MustExist" NUMBER(1,0), 
	"Hidden" NUMBER(1,0), 
	"Format" VARCHAR2(80 CHAR), 
	"PositionX" FLOAT(126), 
	"PositionY" FLOAT(126), 
	"Visible" NUMBER, 
	"Color" NUMBER, 
	"Ratio" NUMBER, 
	"Size" FLOAT(126), 
	"Direction" NUMBER, 
	"Level" NUMBER, 
	"DefaultValue" VARCHAR2(255 CHAR), 
	"ASSIGNED_LIST" VARCHAR2(255 CHAR), 
	"UNIQUE_VALUE" NUMBER, 
	"Flags2" NUMBER, 
	"DESCRIPTION_86" VARCHAR2(255 CHAR), 
	"DESCRIPTION_31" VARCHAR2(255 CHAR), 
	"DESCRIPTION_44" VARCHAR2(255 CHAR), 
	"DESCRIPTION_33" VARCHAR2(255 CHAR), 
	"DESCRIPTION_49" VARCHAR2(255 CHAR), 
	"DESCRIPTION_39" VARCHAR2(255 CHAR), 
	"DESCRIPTION_81" VARCHAR2(255 CHAR), 
	"DESCRIPTION_351" VARCHAR2(255 CHAR), 
	"DESCRIPTION_07" VARCHAR2(255 CHAR), 
	"DESCRIPTION_34" VARCHAR2(255 CHAR), 
	"DESCRIPTION_90" VARCHAR2(255 CHAR), 
	"DESCRIPTION_48" VARCHAR2(255 CHAR), 
	"USAGE_DESCRIPTION" VARCHAR2(50), 
	 PRIMARY KEY ("AttributeName")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."AttributeDefinition" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."AttributeDefinition" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."BlockedInfos" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"RootEntry" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"BlockedPins" BLOB, 
	 PRIMARY KEY ("ENTRY", "VERSION", "RootEntry")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("BlockedPins") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

GRANT SELECT ON "E3_ADMIN"."BlockedInfos" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."BlockedInfos" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."BlockedInfos" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."BlockedInfos" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."BlockedInfos" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."COMPONENT_STATES" 
   (	"ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	"COMP_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"SYMBOL_STATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"GATNUM" NUMBER NOT NULL ENABLE, 
	"ORDER_NUM" NUMBER, 
	 PRIMARY KEY ("ID", "COMP_ID", "SYMBOL_STATE_ID", "GATNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."COMPONENT_STATES" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."COMPONENT_STATES" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."COMPONENT_STATES" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."COMPONENT_STATES" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."COMPONENT_STATES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."CRIMPING_RULES" 
   (	"GUID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"PHSYPIN_ENTRY" VARCHAR2(255 CHAR), 
	"PHYSPIN_PIN_NUMBER" NUMBER, 
	"RULE_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"RULE_TYPE" NUMBER, 
	 PRIMARY KEY ("GUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "E3SERIES" ;

CREATE INDEX "E3_ADMIN"."I_CS_PHSYPIN_ENTRY_PHYSPIN_PIN" ON "E3_ADMIN"."CRIMPING_RULES" ("PHSYPIN_ENTRY", "PHYSPIN_PIN_NUMBER", "RULE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."CRIMPING_RULES" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."CRIMPING_RULES" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."CRIMPING_RULES" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."CRIMPING_RULES" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."CRIMPING_RULES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."CR_ATTRIBUTES" 
   (	"CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"VALUE" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("CRIMPING_RULES_GUID", "NAME", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."CR_ATTRIBUTES" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."CR_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."CR_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."CR_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."CR_ATTRIBUTES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."CR_WIRE_DEFINITIONS" 
   (	"CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"INDEX" NUMBER NOT NULL ENABLE, 
	"MIN_SIZE" FLOAT(126), 
	"MAX_SIZE" FLOAT(126), 
	 PRIMARY KEY ("CRIMPING_RULES_GUID", "INDEX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."CR_WIRE_DEFINITIONS" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."CR_WIRE_DEFINITIONS" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."CR_WIRE_DEFINITIONS" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."CR_WIRE_DEFINITIONS" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."CR_WIRE_DEFINITIONS" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."CR_WIRE_DEFINITION_ATTRIBUTES" 
   (	"CRIMPING_RULES_GUID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"CR_WIRE_DEFINITIONS_INDEX" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"VALUE" VARCHAR2(255 CHAR), 
	"RANGE_MAX" VARCHAR2(255 CHAR), 
	"FLAGS" NUMBER, 
	 PRIMARY KEY ("CRIMPING_RULES_GUID", "CR_WIRE_DEFINITIONS_INDEX", "NAME", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."CR_WIRE_DEFINITION_ATTRIBUTES" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."CR_WIRE_DEFINITION_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."CR_WIRE_DEFINITION_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."CR_WIRE_DEFINITION_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."CR_WIRE_DEFINITION_ATTRIBUTES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Cable" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"BundleID" NUMBER, 
	"ParentID" NUMBER, 
	"Name" VARCHAR2(64 CHAR), 
	"NODENO" NUMBER, 
	"CrossSection" FLOAT(126), 
	"Color" NUMBER, 
	"Flags" NUMBER, 
	"SUBENTRY" VARCHAR2(255 CHAR), 
	"SUBVERSION" VARCHAR2(4 CHAR), 
	"OuterDia" FLOAT(126), 
	 PRIMARY KEY ("ENTRY", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Cable" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."Cable" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Cable" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."Cable" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."Cable" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ColumnDescription" 
   (	"TableName" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"ColumnName" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"English" VARCHAR2(80 CHAR), 
	"German" VARCHAR2(80 CHAR), 
	"French" VARCHAR2(80 CHAR), 
	"Chinese" VARCHAR2(80 CHAR), 
	"Dutch" VARCHAR2(80 CHAR), 
	"Italian" VARCHAR2(80 CHAR), 
	"Japanese" VARCHAR2(80 CHAR), 
	"Polski" VARCHAR2(255 CHAR), 
	"Portuguese" VARCHAR2(80 CHAR), 
	"Russian" VARCHAR2(80 CHAR), 
	"Spanish" VARCHAR2(80 CHAR), 
	"Turkish" VARCHAR2(80 CHAR), 
	 PRIMARY KEY ("TableName", "ColumnName")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."ColumnDescription" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ColumnDescription" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ComponentAttribute" 
   (	"ID" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"BundleID" NUMBER NOT NULL ENABLE, 
	"NODENO" NUMBER NOT NULL ENABLE, 
	"Flags" NUMBER NOT NULL ENABLE, 
	"AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER NOT NULL ENABLE, 
	"AttributeValue" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID", "ENTRY", "VERSION", "BundleID", "NODENO", "Flags", "AttributeName", "Copy")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

CREATE INDEX "E3_ADMIN"."I_Ce_ENTRY_VERSION" ON "E3_ADMIN"."ComponentAttribute" ("ENTRY", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;
  GRANT SELECT ON "E3_ADMIN"."ComponentAttribute" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."ComponentAttribute" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."ComponentAttribute" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ComponentAttribute" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."ComponentAttribute" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ComponentClassification" 
   (	"Name" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"Structure" BLOB, 
	 PRIMARY KEY ("Name")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("Structure") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

GRANT SELECT ON "E3_ADMIN"."ComponentClassification" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ComponentClassification" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ComponentData" 
   (	"ID" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"ENTRY" VARCHAR2(255 CHAR), 
	"VERSION" VARCHAR2(4 CHAR), 
	"DeviceLetterCode" VARCHAR2(4 CHAR), 
	"Class" VARCHAR2(80 CHAR), 
	"ENTRYTYP" NUMBER, 
	"Description" VARCHAR2(255 CHAR), 
	"LPNTR" VARCHAR2(255 CHAR), 
	"VSTATUS" VARCHAR2(1 CHAR), 
	"VersionText" VARCHAR2(80 CHAR), 
	"DATEMAIN" DATE, 
	"LASTUPDT" DATE, 
	"MPNTR" VARCHAR2(255 CHAR), 
	"Flags" NUMBER, 
	"ArticleNumber" VARCHAR2(80 CHAR), 
	"Supplier" VARCHAR2(80 CHAR), 
	"SPNTR" VARCHAR2(20 CHAR), 
	"SUBTYP" NUMBER, 
	"*Normative_doc" VARCHAR2(255), 
	"*Owner" VARCHAR2(80), 
	"*SAP_nomer" VARCHAR2(128), 
	"Class-main" VARCHAR2(80), 
	"TC_ID" VARCHAR2(128), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

CREATE INDEX "E3_ADMIN"."I_Ca_ENTRY_VERSION" ON "E3_ADMIN"."ComponentData" ("ENTRY", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;
  GRANT SELECT ON "E3_ADMIN"."ComponentData" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."ComponentData" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."ComponentData" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ComponentData" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."ComponentData" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ConnectionTypes" 
   (	"ConnectionType" NUMBER NOT NULL ENABLE, 
	"Flags" NUMBER, 
	"DESCRIPTION_86" VARCHAR2(255 CHAR), 
	"DESCRIPTION_31" VARCHAR2(255 CHAR), 
	"DESCRIPTION_44" VARCHAR2(255 CHAR), 
	"DESCRIPTION_33" VARCHAR2(255 CHAR), 
	"DESCRIPTION_49" VARCHAR2(255 CHAR), 
	"DESCRIPTION_39" VARCHAR2(255 CHAR), 
	"DESCRIPTION_81" VARCHAR2(255 CHAR), 
	"DESCRIPTION_351" VARCHAR2(255 CHAR), 
	"DESCRIPTION_07" VARCHAR2(255 CHAR), 
	"DESCRIPTION_34" VARCHAR2(255 CHAR), 
	"DESCRIPTION_90" VARCHAR2(255 CHAR), 
	"DESCRIPTION_48" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ConnectionType")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."ConnectionTypes" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ConnectionTypes" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."CrossSections" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CrossSection" FLOAT(126) NOT NULL ENABLE, 
	"Description" VARCHAR2(255 CHAR), 
	"Flags" NUMBER, 
	"Type" NUMBER, 
	 PRIMARY KEY ("ID", "CrossSection")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."CrossSections" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."CrossSections" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."DatabaseInfo" 
   (	"Version" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"Description" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("Version")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."DatabaseInfo" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."DatabaseInfo" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."DatabaseTree" 
   (	"Structure" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"Data" BLOB, 
	"TreeType" NUMBER NOT NULL ENABLE, 
	"Active" NUMBER(1,0), 
	 PRIMARY KEY ("Structure", "TreeType")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("Data") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

GRANT SELECT ON "E3_ADMIN"."DatabaseTree" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."DatabaseTree" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."DatabaseTree" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."DatabaseTree" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."DatabaseTree" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Drill" 
   (	"EntryID" NUMBER NOT NULL ENABLE, 
	"Diameter" FLOAT(126), 
	"Tolerance" FLOAT(126), 
	"Unit" VARCHAR2(20 CHAR), 
	"Type" NUMBER, 
	"TData" BLOB, 
	 PRIMARY KEY ("EntryID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("TData") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

GRANT SELECT ON "E3_ADMIN"."Drill" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Drill" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ELECTRICAL_ATTRIBUTES" 
   (	"WIREKIND_ID" NUMBER NOT NULL ENABLE, 
	"RELATIVE_PERMITTIVITY" FLOAT(126), 
	"LOSS_ANGLE" FLOAT(126), 
	 PRIMARY KEY ("WIREKIND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."ELECTRICAL_ATTRIBUTES" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ELECTRICAL_ATTRIBUTES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."EXP_SD_13264-11_28_32" 
   (	"PROCESS_ORDER" NUMBER, 
	"DUPLICATE" NUMBER, 
	"DUMP_FILEID" NUMBER, 
	"DUMP_POSITION" NUMBER, 
	"DUMP_LENGTH" NUMBER, 
	"DUMP_ORIG_LENGTH" NUMBER, 
	"DUMP_ALLOCATION" NUMBER, 
	"COMPLETED_ROWS" NUMBER, 
	"ERROR_COUNT" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"OBJECT_TYPE_PATH" VARCHAR2(200), 
	"OBJECT_PATH_SEQNO" NUMBER, 
	"OBJECT_TYPE" VARCHAR2(30), 
	"IN_PROGRESS" CHAR(1), 
	"OBJECT_NAME" VARCHAR2(500), 
	"OBJECT_LONG_NAME" VARCHAR2(4000), 
	"OBJECT_SCHEMA" VARCHAR2(30), 
	"ORIGINAL_OBJECT_SCHEMA" VARCHAR2(30), 
	"ORIGINAL_OBJECT_NAME" VARCHAR2(4000), 
	"PARTITION_NAME" VARCHAR2(30), 
	"SUBPARTITION_NAME" VARCHAR2(30), 
	"DATAOBJ_NUM" NUMBER, 
	"FLAGS" NUMBER, 
	"PROPERTY" NUMBER, 
	"TRIGFLAG" NUMBER, 
	"CREATION_LEVEL" NUMBER, 
	"COMPLETION_TIME" DATE, 
	"OBJECT_TABLESPACE" VARCHAR2(30), 
	"SIZE_ESTIMATE" NUMBER, 
	"OBJECT_ROW" NUMBER, 
	"PROCESSING_STATE" CHAR(1), 
	"PROCESSING_STATUS" CHAR(1), 
	"BASE_PROCESS_ORDER" NUMBER, 
	"BASE_OBJECT_TYPE" VARCHAR2(30), 
	"BASE_OBJECT_NAME" VARCHAR2(30), 
	"BASE_OBJECT_SCHEMA" VARCHAR2(30), 
	"ANCESTOR_PROCESS_ORDER" NUMBER, 
	"DOMAIN_PROCESS_ORDER" NUMBER, 
	"PARALLELIZATION" NUMBER, 
	"UNLOAD_METHOD" NUMBER, 
	"LOAD_METHOD" NUMBER, 
	"GRANULES" NUMBER, 
	"SCN" NUMBER, 
	"GRANTOR" VARCHAR2(30), 
	"XML_CLOB" CLOB, 
	"PARENT_PROCESS_ORDER" NUMBER, 
	"NAME" VARCHAR2(30), 
	"VALUE_T" VARCHAR2(4000), 
	"VALUE_N" NUMBER, 
	"IS_DEFAULT" NUMBER, 
	"FILE_TYPE" NUMBER, 
	"USER_DIRECTORY" VARCHAR2(4000), 
	"USER_FILE_NAME" VARCHAR2(4000), 
	"FILE_NAME" VARCHAR2(4000), 
	"EXTEND_SIZE" NUMBER, 
	"FILE_MAX_SIZE" NUMBER, 
	"PROCESS_NAME" VARCHAR2(30), 
	"LAST_UPDATE" DATE, 
	"WORK_ITEM" VARCHAR2(30), 
	"OBJECT_NUMBER" NUMBER, 
	"COMPLETED_BYTES" NUMBER, 
	"TOTAL_BYTES" NUMBER, 
	"METADATA_IO" NUMBER, 
	"DATA_IO" NUMBER, 
	"CUMULATIVE_TIME" NUMBER, 
	"PACKET_NUMBER" NUMBER, 
	"INSTANCE_ID" NUMBER, 
	"OLD_VALUE" VARCHAR2(4000), 
	"SEED" NUMBER, 
	"LAST_FILE" NUMBER, 
	"USER_NAME" VARCHAR2(30), 
	"OPERATION" VARCHAR2(30), 
	"JOB_MODE" VARCHAR2(30), 
	"QUEUE_TABNUM" NUMBER, 
	"CONTROL_QUEUE" VARCHAR2(30), 
	"STATUS_QUEUE" VARCHAR2(30), 
	"REMOTE_LINK" VARCHAR2(4000), 
	"VERSION" NUMBER, 
	"JOB_VERSION" VARCHAR2(30), 
	"DB_VERSION" VARCHAR2(30), 
	"TIMEZONE" VARCHAR2(64), 
	"STATE" VARCHAR2(30), 
	"PHASE" NUMBER, 
	"GUID" RAW(16), 
	"START_TIME" DATE, 
	"BLOCK_SIZE" NUMBER, 
	"METADATA_BUFFER_SIZE" NUMBER, 
	"DATA_BUFFER_SIZE" NUMBER, 
	"DEGREE" NUMBER, 
	"PLATFORM" VARCHAR2(101), 
	"ABORT_STEP" NUMBER, 
	"INSTANCE" VARCHAR2(60), 
	"CLUSTER_OK" NUMBER, 
	"SERVICE_NAME" VARCHAR2(100), 
	"OBJECT_INT_OID" VARCHAR2(32), 
	 UNIQUE ("PROCESS_ORDER", "DUPLICATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("XML_CLOB") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE INDEX "E3_ADMIN"."SYS_MTABLE_000038103_IND_1" ON "E3_ADMIN"."EXP_SD_13264-11_28_32" ("OBJECT_SCHEMA", "OBJECT_NAME", "OBJECT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;
  CREATE INDEX "E3_ADMIN"."SYS_MTABLE_000038103_IND_2" ON "E3_ADMIN"."EXP_SD_13264-11_28_32" ("BASE_PROCESS_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

COMMENT ON TABLE E3_ADMIN."EXP_SD_13264-11_28_32" IS 'Data Pump Master Table EXPORT                         TABLE                         ';

CREATE TABLE "E3_ADMIN"."EXP_SD_13271-11_39_36" 
   (	"PROCESS_ORDER" NUMBER, 
	"DUPLICATE" NUMBER, 
	"DUMP_FILEID" NUMBER, 
	"DUMP_POSITION" NUMBER, 
	"DUMP_LENGTH" NUMBER, 
	"DUMP_ORIG_LENGTH" NUMBER, 
	"DUMP_ALLOCATION" NUMBER, 
	"COMPLETED_ROWS" NUMBER, 
	"ERROR_COUNT" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"OBJECT_TYPE_PATH" VARCHAR2(200), 
	"OBJECT_PATH_SEQNO" NUMBER, 
	"OBJECT_TYPE" VARCHAR2(30), 
	"IN_PROGRESS" CHAR(1), 
	"OBJECT_NAME" VARCHAR2(500), 
	"OBJECT_LONG_NAME" VARCHAR2(4000), 
	"OBJECT_SCHEMA" VARCHAR2(30), 
	"ORIGINAL_OBJECT_SCHEMA" VARCHAR2(30), 
	"ORIGINAL_OBJECT_NAME" VARCHAR2(4000), 
	"PARTITION_NAME" VARCHAR2(30), 
	"SUBPARTITION_NAME" VARCHAR2(30), 
	"DATAOBJ_NUM" NUMBER, 
	"FLAGS" NUMBER, 
	"PROPERTY" NUMBER, 
	"TRIGFLAG" NUMBER, 
	"CREATION_LEVEL" NUMBER, 
	"COMPLETION_TIME" DATE, 
	"OBJECT_TABLESPACE" VARCHAR2(30), 
	"SIZE_ESTIMATE" NUMBER, 
	"OBJECT_ROW" NUMBER, 
	"PROCESSING_STATE" CHAR(1), 
	"PROCESSING_STATUS" CHAR(1), 
	"BASE_PROCESS_ORDER" NUMBER, 
	"BASE_OBJECT_TYPE" VARCHAR2(30), 
	"BASE_OBJECT_NAME" VARCHAR2(30), 
	"BASE_OBJECT_SCHEMA" VARCHAR2(30), 
	"ANCESTOR_PROCESS_ORDER" NUMBER, 
	"DOMAIN_PROCESS_ORDER" NUMBER, 
	"PARALLELIZATION" NUMBER, 
	"UNLOAD_METHOD" NUMBER, 
	"LOAD_METHOD" NUMBER, 
	"GRANULES" NUMBER, 
	"SCN" NUMBER, 
	"GRANTOR" VARCHAR2(30), 
	"XML_CLOB" CLOB, 
	"PARENT_PROCESS_ORDER" NUMBER, 
	"NAME" VARCHAR2(30), 
	"VALUE_T" VARCHAR2(4000), 
	"VALUE_N" NUMBER, 
	"IS_DEFAULT" NUMBER, 
	"FILE_TYPE" NUMBER, 
	"USER_DIRECTORY" VARCHAR2(4000), 
	"USER_FILE_NAME" VARCHAR2(4000), 
	"FILE_NAME" VARCHAR2(4000), 
	"EXTEND_SIZE" NUMBER, 
	"FILE_MAX_SIZE" NUMBER, 
	"PROCESS_NAME" VARCHAR2(30), 
	"LAST_UPDATE" DATE, 
	"WORK_ITEM" VARCHAR2(30), 
	"OBJECT_NUMBER" NUMBER, 
	"COMPLETED_BYTES" NUMBER, 
	"TOTAL_BYTES" NUMBER, 
	"METADATA_IO" NUMBER, 
	"DATA_IO" NUMBER, 
	"CUMULATIVE_TIME" NUMBER, 
	"PACKET_NUMBER" NUMBER, 
	"INSTANCE_ID" NUMBER, 
	"OLD_VALUE" VARCHAR2(4000), 
	"SEED" NUMBER, 
	"LAST_FILE" NUMBER, 
	"USER_NAME" VARCHAR2(30), 
	"OPERATION" VARCHAR2(30), 
	"JOB_MODE" VARCHAR2(30), 
	"QUEUE_TABNUM" NUMBER, 
	"CONTROL_QUEUE" VARCHAR2(30), 
	"STATUS_QUEUE" VARCHAR2(30), 
	"REMOTE_LINK" VARCHAR2(4000), 
	"VERSION" NUMBER, 
	"JOB_VERSION" VARCHAR2(30), 
	"DB_VERSION" VARCHAR2(30), 
	"TIMEZONE" VARCHAR2(64), 
	"STATE" VARCHAR2(30), 
	"PHASE" NUMBER, 
	"GUID" RAW(16), 
	"START_TIME" DATE, 
	"BLOCK_SIZE" NUMBER, 
	"METADATA_BUFFER_SIZE" NUMBER, 
	"DATA_BUFFER_SIZE" NUMBER, 
	"DEGREE" NUMBER, 
	"PLATFORM" VARCHAR2(101), 
	"ABORT_STEP" NUMBER, 
	"INSTANCE" VARCHAR2(60), 
	"CLUSTER_OK" NUMBER, 
	"SERVICE_NAME" VARCHAR2(100), 
	"OBJECT_INT_OID" VARCHAR2(32), 
	 UNIQUE ("PROCESS_ORDER", "DUPLICATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("XML_CLOB") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE INDEX "E3_ADMIN"."SYS_MTABLE_00003813F_IND_1" ON "E3_ADMIN"."EXP_SD_13271-11_39_36" ("OBJECT_SCHEMA", "OBJECT_NAME", "OBJECT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;
  CREATE INDEX "E3_ADMIN"."SYS_MTABLE_00003813F_IND_2" ON "E3_ADMIN"."EXP_SD_13271-11_39_36" ("BASE_PROCESS_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

COMMENT ON TABLE E3_ADMIN."EXP_SD_13271-11_39_36" IS 'Data Pump Master Table EXPORT                         SCHEMA                        ';

CREATE TABLE "E3_ADMIN"."FAVORITES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	"TYPE" NUMBER, 
	"SEQUENCE" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."FAVORITES" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."FAVORITES" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."FAVORITES" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."FAVORITES" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."FAVORITES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."FAVORITE_VALUES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"DBFIELD" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"VALUE" VARCHAR2(255 CHAR), 
	"FLAGS" NUMBER, 
	 PRIMARY KEY ("ID", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."FAVORITE_VALUES" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."FAVORITE_VALUES" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."FAVORITE_VALUES" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."FAVORITE_VALUES" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."FAVORITE_VALUES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."FUNCTIONAL_ASSIGNMENTS" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PINCOPY" NUMBER NOT NULL ENABLE, 
	"FUNAME" VARCHAR2(255 CHAR), 
	"FUID" NUMBER, 
	"FUPORT" NUMBER, 
	 PRIMARY KEY ("ENTRY", "VERSION", "NAME", "PINCOPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."FUNCTIONAL_ASSIGNMENTS" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."FUNCTIONAL_ASSIGNMENTS" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."FUNCTIONAL_ASSIGNMENTS" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."FUNCTIONAL_ASSIGNMENTS" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."FUNCTIONAL_ASSIGNMENTS" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."FUNCTIONAL_PORTS" 
   (	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"PORT" VARCHAR2(255 CHAR), 
	"FLAGS" NUMBER, 
	 PRIMARY KEY ("NAME", "ID", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."FUNCTIONAL_PORTS" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."FUNCTIONAL_PORTS" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."FUNCTIONAL_UNITS" 
   (	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"SYMBOL" VARCHAR2(255 CHAR), 
	"TYPE" NUMBER, 
	 PRIMARY KEY ("NAME", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."FUNCTIONAL_UNITS" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."FUNCTIONAL_UNITS" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."FUNCTIONAL_UNIT_STATES" 
   (	"ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	"FU_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"FU_ID" NUMBER NOT NULL ENABLE, 
	"ORDER_NUM" NUMBER, 
	"FLAGS" NUMBER, 
	 PRIMARY KEY ("ID", "FU_NAME", "FU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."FUNCTIONAL_UNIT_STATES" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."FUNCTIONAL_UNIT_STATES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."FUNCTION_ATTRIBUTES" 
   (	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"PORT_NUMBER" NUMBER NOT NULL ENABLE, 
	"ATTRIBUTE_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"STATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"ATTRIBUTE_VALUE" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("NAME", "ID", "PORT_NUMBER", "ATTRIBUTE_NAME", "COPY", "STATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."FUNCTION_ATTRIBUTES" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."FUNCTION_ATTRIBUTES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."GATE_FUNCTION_ATTRIBUTES" 
   (	"LPNTR" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"GateNumber" NUMBER NOT NULL ENABLE, 
	"FUSUBID" NUMBER NOT NULL ENABLE, 
	"STATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER NOT NULL ENABLE, 
	"AttributeValue" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("LPNTR", "GateNumber", "FUSUBID", "STATE_ID", "AttributeName", "Copy")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."GATE_FUNCTION_ATTRIBUTES" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."GATE_FUNCTION_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."GATE_FUNCTION_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."GATE_FUNCTION_ATTRIBUTES" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."GATE_FUNCTION_ATTRIBUTES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Gate" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"CCTNAME" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ENTRY", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Gate" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."Gate" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."Gate" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Gate" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."Gate" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."GatePinRelation" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"GateNumber" NUMBER NOT NULL ENABLE, 
	"PinNumber" NUMBER NOT NULL ENABLE, 
	"Representation" NUMBER NOT NULL ENABLE, 
	"NodeNumber" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ENTRY", "GateNumber", "PinNumber", "Representation", "NodeNumber")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."GatePinRelation" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."GatePinRelation" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."GatePinRelation" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."GatePinRelation" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."GatePinRelation" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."IEC 750 letter codes" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LetterCode" VARCHAR2(255 CHAR), 
	"ValueRange" VARCHAR2(255 CHAR), 
	"Class" VARCHAR2(255 CHAR), 
	"Klasse" VARCHAR2(255 CHAR), 
	"Classe" VARCHAR2(255 CHAR), 
	"Clase" VARCHAR2(255 CHAR), 
	"Eeann" VARCHAR2(256 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."IEC 750 letter codes" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."IEC 750 letter codes" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."LOCKINFO" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"TYPE" NUMBER NOT NULL ENABLE, 
	"USER" VARCHAR2(255 CHAR), 
	"HOST" VARCHAR2(255 CHAR), 
	"PID" NUMBER, 
	"TIME" NUMBER, 
	 PRIMARY KEY ("ENTRY", "VERSION", "TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."LOCKINFO" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."LOCKINFO" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."LOCKINFO" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."LOCKINFO" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."LOCKINFO" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Languages" 
   (	"<mainClass>" VARCHAR2(255 CHAR), 
	"<subClass>" VARCHAR2(255 CHAR), 
	"American English" VARCHAR2(255 CHAR), 
	"British English" VARCHAR2(255 CHAR), 
	"Castellano" VARCHAR2(255 CHAR), 
	"Chinese" VARCHAR2(255 CHAR), 
	"Chinese(CHT)" VARCHAR2(255 CHAR), 
	"Description" VARCHAR2(255 CHAR), 
	"Deutsch" VARCHAR2(255 CHAR), 
	"Francais" VARCHAR2(255 CHAR), 
	"ID" NUMBER NOT NULL ENABLE, 
	"Italiano" VARCHAR2(255 CHAR), 
	"Japanese" VARCHAR2(255 CHAR), 
	"Nederlands" VARCHAR2(255 CHAR), 
	"Pictogram" VARCHAR2(255 CHAR), 
	"Polski" VARCHAR2(255 CHAR), 
	"Russian" VARCHAR2(255 CHAR), 
	"Swedish" VARCHAR2(255 CHAR), 
	"Turkish" VARCHAR2(255 CHAR), 
	"Portugues" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Languages" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."Languages" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."Languages" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Languages" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."Languages" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Layer" 
   (	"EntryID" NUMBER NOT NULL ENABLE, 
	"LayerName" VARCHAR2(20 CHAR), 
	 PRIMARY KEY ("EntryID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Layer" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Layer" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."LogicAttribute" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"GateNumber" NUMBER NOT NULL ENABLE, 
	"AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER NOT NULL ENABLE, 
	"AttributeValue" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ENTRY", "GateNumber", "AttributeName", "Copy")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."LogicAttribute" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."LogicAttribute" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."LogicAttribute" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."LogicAttribute" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."LogicAttribute" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."MATERIAL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"RESISTIVITY_TEMP" FLOAT(126), 
	"THERMAL_CAP" FLOAT(126), 
	"GRAVITY" FLOAT(126), 
	"RESISTANCE" FLOAT(126), 
	"SPECIFIC_RESISTANCE" FLOAT(126), 
	 PRIMARY KEY ("ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."MATERIAL" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."MATERIAL" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ModelAttribute" 
   (	"ID" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER NOT NULL ENABLE, 
	"AttributeValue" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID", "Entry", "AttributeName", "Copy")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

CREATE INDEX "E3_ADMIN"."I_Me_Entry" ON "E3_ADMIN"."ModelAttribute" ("Entry") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;
  GRANT SELECT ON "E3_ADMIN"."ModelAttribute" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."ModelAttribute" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."ModelAttribute" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ModelAttribute" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."ModelAttribute" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ModelData" 
   (	"ID" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"Entry" VARCHAR2(255 CHAR), 
	"Type" NUMBER, 
	"Class" VARCHAR2(80 CHAR), 
	"Description" VARCHAR2(255 CHAR), 
	"LASTUPDT" DATE, 
	"DATEMAIN" DATE, 
	"*Owner" VARCHAR2(255), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

CREATE INDEX "E3_ADMIN"."I_Ma_Entry" ON "E3_ADMIN"."ModelData" ("Entry") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;
  GRANT SELECT ON "E3_ADMIN"."ModelData" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."ModelData" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."ModelData" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ModelData" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."ModelData" TO "E3WRITER_ROLE";


CREATE TABLE "E3_ADMIN"."OUTDATED" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "E3SERIES" ;

CREATE TABLE "E3_ADMIN"."OutlineSymbols" 
   (	"Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"OutlineNumber" NUMBER NOT NULL ENABLE, 
	"ViewNumber" NUMBER NOT NULL ENABLE, 
	"Symbol" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("Entry", "OutlineNumber", "ViewNumber", "Symbol")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."OutlineSymbols" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."OutlineSymbols" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."OutlineSymbols" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."OutlineSymbols" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."OutlineSymbols" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Outlines" 
   (	"Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"OutlineNumber" NUMBER NOT NULL ENABLE, 
	"Type" NUMBER, 
	"X" FLOAT(126), 
	"Y" FLOAT(126), 
	"Z" FLOAT(126), 
	"LineY" FLOAT(126), 
	"LineZ" FLOAT(126), 
	"AreaZ" FLOAT(126), 
	"Height" FLOAT(126), 
	"OutlineData" BLOB, 
	"RestrictedLayer" NUMBER, 
	"DescriptionLevel" NUMBER, 
	"Flags" NUMBER, 
	 PRIMARY KEY ("Entry", "OutlineNumber")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("OutlineData") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

GRANT SELECT ON "E3_ADMIN"."Outlines" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."Outlines" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."Outlines" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Outlines" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."Outlines" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."PadStack" 
   (	"EntryID" NUMBER NOT NULL ENABLE, 
	"PadSym" VARCHAR2(20 CHAR), 
	"LayerID" NUMBER NOT NULL ENABLE, 
	"Flags" NUMBER, 
	 PRIMARY KEY ("EntryID", "LayerID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."PadStack" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."PadStack" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."PenDefinition" 
   (	"Type" NUMBER NOT NULL ENABLE, 
	"ColorIndex" NUMBER, 
	"PenStyle" NUMBER, 
	"PenWidth" FLOAT(126), 
	 PRIMARY KEY ("Type")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."PenDefinition" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."PenDefinition" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."PhysPin" 
   (	"Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PinNumber" NUMBER NOT NULL ENABLE, 
	"ConnX" FLOAT(126), 
	"ConnY" FLOAT(126), 
	"ConnZ" FLOAT(126), 
	"ConnType" NUMBER, 
	"ConnDirection" NUMBER, 
	"WireColor" NUMBER, 
	"ConnDimension1" FLOAT(126), 
	"ConnDimension2" FLOAT(126), 
	"AWGMin" FLOAT(126), 
	"AWGMax" FLOAT(126), 
	"ConnDimensionMax" FLOAT(126), 
	"WireMax" NUMBER, 
	"SpineX" FLOAT(126), 
	"SpineY" FLOAT(126), 
	"SpineZ" FLOAT(126), 
	"SlopeAngle" FLOAT(126), 
	"PluggableDepth" FLOAT(126), 
	"PinCode" NUMBER, 
	"PinLayer" NUMBER, 
	"PinRotation" FLOAT(126), 
	"TestPointCode" NUMBER, 
	"TechStackS" VARCHAR2(20 CHAR), 
	"TechStackC" VARCHAR2(20 CHAR), 
	"DrillID" NUMBER, 
	"Flags2" NUMBER, 
	 PRIMARY KEY ("Entry", "PinNumber")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."PhysPin" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."PhysPin" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."PhysPin" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."PhysPin" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."PhysPin" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Pin" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"PHYSPIN" VARCHAR2(64 CHAR), 
	"FUNCT" NUMBER, 
	"PINEQUIV" NUMBER, 
	"LPINEQV" NUMBER, 
	"PINNAME" VARCHAR2(200 CHAR), 
	"NPINEQV" NUMBER, 
	"Flags" NUMBER, 
	"TPNPRIO" NUMBER, 
	"FLAGS2" NUMBER, 
	 PRIMARY KEY ("ENTRY", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Pin" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."Pin" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."Pin" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Pin" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."Pin" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."PinAttribute" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PinNumber" NUMBER, 
	"AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER NOT NULL ENABLE, 
	"AttributeValue" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ENTRY", "PinNumber", "AttributeName", "Copy")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."PinAttribute" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."PinAttribute" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."PinAttribute" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."PinAttribute" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."PinAttribute" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."PinDesign" 
   (	"Entry" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER, 
	"TechnologyID" NUMBER NOT NULL ENABLE, 
	"PadStackID" NUMBER, 
	 PRIMARY KEY ("Entry", "TechnologyID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."PinDesign" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."PinDesign" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."PlugInfo" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"PINCOMP" VARCHAR2(255 CHAR), 
	"ActiveCounterPart" NUMBER(1,0), 
	"PINPART" VARCHAR2(255 CHAR), 
	"ActiveFittingPart" NUMBER(1,0), 
	"PinNumber" NUMBER, 
	"ActiveWireSeal" NUMBER(1,0), 
	 PRIMARY KEY ("ENTRY", "VERSION", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."PlugInfo" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."PlugInfo" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."PlugInfo" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."PlugInfo" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."PlugInfo" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."RetainingRailTypes" 
   (	"Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"Type" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("Entry", "Type")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."RetainingRailTypes" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."RetainingRailTypes" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."RetainingRailTypes" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."RetainingRailTypes" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."RetainingRailTypes" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SETTINGS" 
   (	"PARAM" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("PARAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SETTINGS" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SETTINGS" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SYMBOL_FUNCTION" 
   (	"LPNTR" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LBNNUM" NUMBER NOT NULL ENABLE, 
	"FUSUBID" NUMBER NOT NULL ENABLE, 
	"FUNAME" VARCHAR2(255 CHAR), 
	"FUID" NUMBER, 
	"FUPORT" NUMBER, 
	 PRIMARY KEY ("LPNTR", "LBNNUM", "FUSUBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SYMBOL_FUNCTION" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SYMBOL_FUNCTION" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SYMBOL_FUNCTION" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SYMBOL_FUNCTION" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SYMBOL_FUNCTION" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SYMBOL_STATES" 
   (	"ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	"SYMBOL_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"FU_STATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"FUSUBID" NUMBER NOT NULL ENABLE, 
	"ORDER_NUM" NUMBER, 
	"FLAGS" NUMBER, 
	 PRIMARY KEY ("ID", "SYMBOL_ID", "FU_STATE_ID", "FUSUBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SYMBOL_STATES" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SYMBOL_STATES" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SYMBOL_STATES" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SYMBOL_STATES" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SYMBOL_STATES" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SchematicTypes" 
   (	"Type" NUMBER NOT NULL ENABLE, 
	"IconUnplaced" BLOB, 
	"IconPlaced" BLOB, 
	"IconInactive" BLOB, 
	"DESCRIPTION_86" VARCHAR2(255 CHAR), 
	"DESCRIPTION_31" VARCHAR2(255 CHAR), 
	"DESCRIPTION_44" VARCHAR2(255 CHAR), 
	"DESCRIPTION_33" VARCHAR2(255 CHAR), 
	"DESCRIPTION_49" VARCHAR2(255 CHAR), 
	"DESCRIPTION_39" VARCHAR2(255 CHAR), 
	"DESCRIPTION_81" VARCHAR2(255 CHAR), 
	"DESCRIPTION_351" VARCHAR2(255 CHAR), 
	"DESCRIPTION_07" VARCHAR2(255 CHAR), 
	"DESCRIPTION_34" VARCHAR2(255 CHAR), 
	"DESCRIPTION_90" VARCHAR2(255 CHAR), 
	"DESCRIPTION_48" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("Type")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("IconUnplaced") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IconPlaced") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IconInactive") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

GRANT SELECT ON "E3_ADMIN"."SchematicTypes" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SchematicTypes" TO "E3WRITER_ROLE";


CREATE TABLE "E3_ADMIN"."SheetInformation" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SheetType" NUMBER, 
	"LayoutType" NUMBER, 
	"HorzLayout" BLOB, 
	"VertLayout" BLOB, 
	"Orientation" VARCHAR2(12 CHAR), 
	"DrawingArea" BLOB, 
	"PRINT_AREA" RAW(24), 
	 PRIMARY KEY ("ENTRY") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("HorzLayout") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("VertLayout") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DrawingArea") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

GRANT SELECT ON "E3_ADMIN"."SheetInformation" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SheetInformation" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SheetInformation" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SheetInformation" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SheetInformation" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SlotAttribute" 
   (	"Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SlotNumber" NUMBER NOT NULL ENABLE, 
	"AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER NOT NULL ENABLE, 
	"AttributeValue" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("Entry", "SlotNumber", "AttributeName", "Copy")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SlotAttribute" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SlotAttribute" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SlotAttribute" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SlotAttribute" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SlotAttribute" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Slots" 
   (	"Entry" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER NOT NULL ENABLE, 
	"Type" NUMBER, 
	"RetainingRailType" NUMBER, 
	"x1" FLOAT(126), 
	"y1" FLOAT(126), 
	"z1" FLOAT(126), 
	"x2" FLOAT(126), 
	"y2" FLOAT(126), 
	"z2" FLOAT(126), 
	"Width" FLOAT(126), 
	 PRIMARY KEY ("Entry", "Copy")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Slots" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."Slots" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."Slots" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Slots" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."Slots" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Supply" 
   (	"ENTRY" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"Potentialnummer" NUMBER NOT NULL ENABLE, 
	"Potentialname" VARCHAR2(20 CHAR), 
	 PRIMARY KEY ("ENTRY", "Potentialnummer")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Supply" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Supply" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SymbolAttribute" 
   (	"ID" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"AttributeName" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"Copy" NUMBER NOT NULL ENABLE, 
	"AttributeValue" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID", "ENTRY", "VERSION", "AttributeName", "Copy")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

CREATE INDEX "E3_ADMIN"."I_Se_ENTRY_VERSION" ON "E3_ADMIN"."SymbolAttribute" ("ENTRY", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SymbolAttribute" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SymbolAttribute" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SymbolAttribute" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SymbolAttribute" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SymbolAttribute" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SymbolData" 
   (	"ID" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"ENTRY" VARCHAR2(255 CHAR), 
	"VERSION" VARCHAR2(4 CHAR), 
	"Norm" NUMBER, 
	"LSHDES" VARCHAR2(4 CHAR), 
	"LSHTYP" NUMBER, 
	"ENTRYTYP" NUMBER, 
	"LPNTR" VARCHAR2(255 CHAR), 
	"VSTATUS" VARCHAR2(1 CHAR), 
	"VersionText" VARCHAR2(80 CHAR), 
	"DATEMAIN" DATE, 
	"LASTUPDT" DATE, 
	"Class" VARCHAR2(80 CHAR), 
	"Description" VARCHAR2(255 CHAR), 
	"SYMINDEX" NUMBER, 
	"FLAGS2" NUMBER, 
	"FLAGS" NUMBER, 
	"SUBTYP" NUMBER, 
	"*Owner" VARCHAR2(255), 
	"*Normative_doc" VARCHAR2(255), 
	"Class-main" VARCHAR2(80), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

CREATE INDEX "E3_ADMIN"."I_Sa_ENTRY_VERSION_Norm" ON "E3_ADMIN"."SymbolData" ("ENTRY", "VERSION", "Norm") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SymbolData" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SymbolData" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SymbolData" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SymbolData" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SymbolData" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SymbolDimension" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LSHX1" FLOAT(126), 
	"LSHY1" FLOAT(126), 
	"LSHX2" FLOAT(126), 
	"LSHY2" FLOAT(126), 
	 PRIMARY KEY ("ENTRY") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SymbolDimension" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SymbolDimension" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SymbolDimension" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SymbolDimension" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SymbolDimension" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SymbolGraphic" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"GraphicType" NUMBER, 
	"Linecolor" NUMBER, 
	"Linetype" NUMBER, 
	"Linewidth" FLOAT(126), 
	"Fillmode" NUMBER, 
	"Fillcolor" NUMBER, 
	"HatchData" RAW(56), 
	"GraphicData" BLOB, 
	"GraphicLevel" NUMBER, 
	"Flags" NUMBER, 
	"ID" NUMBER, 
	"STATE_ID" VARCHAR2(36 CHAR), 
	 PRIMARY KEY ("ENTRY", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" 
 LOB ("GraphicData") STORE AS BASICFILE (
  TABLESPACE "E3SERIES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

GRANT SELECT ON "E3_ADMIN"."SymbolGraphic" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SymbolGraphic" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SymbolGraphic" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SymbolGraphic" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SymbolGraphic" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SymbolNodes" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"LIBNTY" NUMBER, 
	"LIBNX" FLOAT(126), 
	"LIBNY" FLOAT(126), 
	"LBSTUB" NUMBER, 
	"LBNNUM" NUMBER, 
	"Function" NUMBER, 
	 PRIMARY KEY ("ENTRY", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SymbolNodes" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SymbolNodes" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SymbolNodes" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SymbolNodes" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SymbolNodes" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SymbolPoints" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"FLAGS" NUMBER, 
	"POSX" FLOAT(126), 
	"POSY" FLOAT(126), 
	 PRIMARY KEY ("ENTRY", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SymbolPoints" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SymbolPoints" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SymbolPoints" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SymbolPoints" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SymbolPoints" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."SymbolText" 
   (	"ENTRY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COPY" NUMBER NOT NULL ENABLE, 
	"TTYPE" NUMBER, 
	"TX" FLOAT(126), 
	"TY" FLOAT(126), 
	"TJUST" NUMBER, 
	"THT" FLOAT(126), 
	"TMOD" NUMBER, 
	"TLEV" NUMBER, 
	"TSTR" VARCHAR2(255 CHAR), 
	"LBNNUM" NUMBER, 
	"Flags" NUMBER, 
	"TROT" FLOAT(126), 
	"FontName" VARCHAR2(255 CHAR), 
	"FontStyle" NUMBER, 
	"TextColor" NUMBER, 
	"Flags2" NUMBER, 
	"SIZEX" FLOAT(126), 
	"SIZEY" FLOAT(126), 
	"Hyperlink" VARCHAR2(255 CHAR), 
	"SOURCE" NUMBER, 
	 PRIMARY KEY ("ENTRY", "COPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."SymbolText" TO "E3USER_ROLE";
  GRANT DELETE ON "E3_ADMIN"."SymbolText" TO "E3WRITER_ROLE";
  GRANT INSERT ON "E3_ADMIN"."SymbolText" TO "E3WRITER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."SymbolText" TO "E3WRITER_ROLE";
  GRANT UPDATE ON "E3_ADMIN"."SymbolText" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."Technology" 
   (	"EntryID" NUMBER NOT NULL ENABLE, 
	"Description" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("EntryID", "Description")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."Technology" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."Technology" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."TextInformation" 
   (	"TextType" NUMBER NOT NULL ENABLE, 
	"MaxLength" NUMBER, 
	"Format" VARCHAR2(80 CHAR), 
	"SheetInfo" NUMBER(1,0), 
	"CopyFromSelectedSheet" NUMBER(1,0), 
	"ChangeableByScriptOnly" NUMBER(1,0), 
	"CanModify" NUMBER(1,0), 
	"CanHide" NUMBER(1,0), 
	"CanModifyInivisible" NUMBER(1,0), 
	"DatabaseField" VARCHAR2(255 CHAR), 
	"SystemDefined" NUMBER(1,0), 
	"ConnectionTargetFormat" NUMBER(1,0), 
	"UseActivePinTerminal" NUMBER(1,0), 
	"TEXTNAME_86" VARCHAR2(255 CHAR), 
	"TEXTNAME_31" VARCHAR2(255 CHAR), 
	"TEXTNAME_44" VARCHAR2(255 CHAR), 
	"TEXTNAME_33" VARCHAR2(255 CHAR), 
	"TEXTNAME_49" VARCHAR2(255 CHAR), 
	"TEXTNAME_39" VARCHAR2(255 CHAR), 
	"TEXTNAME_81" VARCHAR2(255 CHAR), 
	"TEXTNAME_351" VARCHAR2(255 CHAR), 
	"TEXTNAME_07" VARCHAR2(255 CHAR), 
	"TEXTNAME_34" VARCHAR2(255 CHAR), 
	"TEXTNAME_90" VARCHAR2(255 CHAR), 
	"TEXTNAME_48" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("TextType")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."TextInformation" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."TextInformation" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."TwistedPairs" 
   (	"CrossSection" FLOAT(126) NOT NULL ENABLE, 
	"OuterDiameter" FLOAT(126) NOT NULL ENABLE, 
	"NumberOfWires" NUMBER NOT NULL ENABLE, 
	"NumberOfTurns" NUMBER, 
	"TwistedLengthFactor" FLOAT(126) NOT NULL ENABLE, 
	 PRIMARY KEY ("CrossSection", "OuterDiameter", "NumberOfWires", "TwistedLengthFactor")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."TwistedPairs" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."TwistedPairs" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."ValidRetainingRailTypes" 
   (	"Type" NUMBER NOT NULL ENABLE, 
	"Description" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("Type", "Description")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."ValidRetainingRailTypes" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."ValidRetainingRailTypes" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."WIREKIND" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MATID1" NUMBER NOT NULL ENABLE, 
	"MATID2" NUMBER, 
	"ALLOW_TEMP" FLOAT(126), 
	"MELTING_TEMP" FLOAT(126), 
	"DESCRIPTION_86" VARCHAR2(255 CHAR), 
	"DESCRIPTION_31" VARCHAR2(255 CHAR), 
	"DESCRIPTION_44" VARCHAR2(255 CHAR), 
	"DESCRIPTION_33" VARCHAR2(255 CHAR), 
	"DESCRIPTION_49" VARCHAR2(255 CHAR), 
	"DESCRIPTION_39" VARCHAR2(255 CHAR), 
	"DESCRIPTION_81" VARCHAR2(255 CHAR), 
	"DESCRIPTION_351" VARCHAR2(255 CHAR), 
	"DESCRIPTION_07" VARCHAR2(255 CHAR), 
	"DESCRIPTION_34" VARCHAR2(255 CHAR), 
	"DESCRIPTION_90" VARCHAR2(255 CHAR), 
	"DESCRIPTION_48" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID", "MATID1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."WIREKIND" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."WIREKIND" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."WIRESIZE" 
   (	"CROSSEC" FLOAT(126) NOT NULL ENABLE, 
	"MATID" NUMBER NOT NULL ENABLE, 
	"RESISTANCE" FLOAT(126), 
	"INNER_DIA" FLOAT(126), 
	"OUTER_DIA" FLOAT(126) NOT NULL ENABLE, 
	 PRIMARY KEY ("CROSSEC", "MATID", "OUTER_DIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."WIRESIZE" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."WIRESIZE" TO "E3WRITER_ROLE";

CREATE TABLE "E3_ADMIN"."WireColorCodes" 
   (	"ColorCode" NUMBER NOT NULL ENABLE, 
	"Color" NUMBER, 
	"Linetype" NUMBER, 
	"Type" NUMBER, 
	"DESCRIPTION_86" VARCHAR2(255 CHAR), 
	"DESCRIPTION_31" VARCHAR2(255 CHAR), 
	"DESCRIPTION_44" VARCHAR2(255 CHAR), 
	"DESCRIPTION_33" VARCHAR2(255 CHAR), 
	"DESCRIPTION_49" VARCHAR2(255 CHAR), 
	"DESCRIPTION_39" VARCHAR2(255 CHAR), 
	"DESCRIPTION_81" VARCHAR2(255 CHAR), 
	"DESCRIPTION_351" VARCHAR2(255 CHAR), 
	"DESCRIPTION_07" VARCHAR2(255 CHAR), 
	"DESCRIPTION_34" VARCHAR2(255 CHAR), 
	"DESCRIPTION_90" VARCHAR2(255 CHAR), 
	"DESCRIPTION_48" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ColorCode")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "E3SERIES" ;

GRANT SELECT ON "E3_ADMIN"."WireColorCodes" TO "E3USER_ROLE";
  GRANT SELECT ON "E3_ADMIN"."WireColorCodes" TO "E3WRITER_ROLE";


CREATE OR REPLACE FORCE VIEW "E3_ADMIN"."NEWVIEW" ("Name", "ID", "ENTRY") AS 
SELECT sd.ENTRY AS "Name", sd.LPNTR AS "ID", sg.ENTRY
FROM "E3_ADMIN"."SymbolData" sd 
RIGHT JOIN "E3_ADMIN"."SymbolGraphic" sg ON sd.LPNTR = sg.ENTRY
WHERE sd.ENTRY IS NULL;

CREATE OR REPLACE FORCE VIEW "E3_ADMIN"."SearchSymbolsOfComp" ("compEntry", "Количество символов", "Class", "compDesc", "*Owner", "Номер символа", "symbolEntry", "symbolDesc") AS 
  SELECT cd.ENTRY AS "compEntry", 
  count(sd.ENTRY) OVER (PARTITION BY cd.ENTRY) AS "Количество символов",
  cd."Class", 
  cd."Description" AS "compDesc", 
  cd."*Owner", 
  ROW_NUMBER() OVER (PARTITION BY cd.ENTRY ORDER BY sd.ENTRY) AS "Номер символа",
  sd.ENTRY AS "symbolEntry", 
  sd."Description" AS "symbolDesc"
FROM E3_ADMIN."ComponentData" cd
JOIN E3_ADMIN."Gate" g ON cd.LPNTR = g.ENTRY 
JOIN E3_ADMIN."SymbolData" sd ON g.CCTNAME = sd.ENTRY
ORDER BY cd."Description", "Номер символа"
--WHERE cd."Description" = '';